// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: usecases/eg/lpc/messages.proto

package lpc

import (
	common_types "github.com/enbility/eebus-grpc/rpc_services/common_types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumptionLimitRequest struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConsumptionLimitRequest) Reset() {
	*x = ConsumptionLimitRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionLimitRequest) ProtoMessage() {}

func (x *ConsumptionLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionLimitRequest.ProtoReflect.Descriptor instead.
func (*ConsumptionLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumptionLimitRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *ConsumptionLimitRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

type ConsumptionLimitResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Limit         *common_types.LoadLimit `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumptionLimitResponse) Reset() {
	*x = ConsumptionLimitResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionLimitResponse) ProtoMessage() {}

func (x *ConsumptionLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionLimitResponse.ProtoReflect.Descriptor instead.
func (*ConsumptionLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumptionLimitResponse) GetLimit() *common_types.LoadLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type WriteConsumptionLimitRequest struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	Limit               *common_types.LoadLimit     `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WriteConsumptionLimitRequest) Reset() {
	*x = WriteConsumptionLimitRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConsumptionLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConsumptionLimitRequest) ProtoMessage() {}

func (x *WriteConsumptionLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConsumptionLimitRequest.ProtoReflect.Descriptor instead.
func (*WriteConsumptionLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{2}
}

func (x *WriteConsumptionLimitRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *WriteConsumptionLimitRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

func (x *WriteConsumptionLimitRequest) GetLimit() *common_types.LoadLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type WriteConsumptionLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorNumber   *uint64                `protobuf:"varint,1,opt,name=error_number,json=errorNumber,proto3,oneof" json:"error_number,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	MsgCounter    uint64                 `protobuf:"varint,3,opt,name=msg_counter,json=msgCounter,proto3" json:"msg_counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteConsumptionLimitResponse) Reset() {
	*x = WriteConsumptionLimitResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConsumptionLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConsumptionLimitResponse) ProtoMessage() {}

func (x *WriteConsumptionLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConsumptionLimitResponse.ProtoReflect.Descriptor instead.
func (*WriteConsumptionLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{3}
}

func (x *WriteConsumptionLimitResponse) GetErrorNumber() uint64 {
	if x != nil && x.ErrorNumber != nil {
		return *x.ErrorNumber
	}
	return 0
}

func (x *WriteConsumptionLimitResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *WriteConsumptionLimitResponse) GetMsgCounter() uint64 {
	if x != nil {
		return x.MsgCounter
	}
	return 0
}

type FailsafeConsumptionActivePowerLimitRequest struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FailsafeConsumptionActivePowerLimitRequest) Reset() {
	*x = FailsafeConsumptionActivePowerLimitRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeConsumptionActivePowerLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeConsumptionActivePowerLimitRequest) ProtoMessage() {}

func (x *FailsafeConsumptionActivePowerLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeConsumptionActivePowerLimitRequest.ProtoReflect.Descriptor instead.
func (*FailsafeConsumptionActivePowerLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{4}
}

func (x *FailsafeConsumptionActivePowerLimitRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *FailsafeConsumptionActivePowerLimitRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

type FailsafeConsumptionActivePowerLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         float64                `protobuf:"fixed64,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailsafeConsumptionActivePowerLimitResponse) Reset() {
	*x = FailsafeConsumptionActivePowerLimitResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeConsumptionActivePowerLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeConsumptionActivePowerLimitResponse) ProtoMessage() {}

func (x *FailsafeConsumptionActivePowerLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeConsumptionActivePowerLimitResponse.ProtoReflect.Descriptor instead.
func (*FailsafeConsumptionActivePowerLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{5}
}

func (x *FailsafeConsumptionActivePowerLimitResponse) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type WriteFailsafeConsumptionActivePowerLimitRequest struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	Limit               float64                     `protobuf:"fixed64,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) Reset() {
	*x = WriteFailsafeConsumptionActivePowerLimitRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFailsafeConsumptionActivePowerLimitRequest) ProtoMessage() {}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFailsafeConsumptionActivePowerLimitRequest.ProtoReflect.Descriptor instead.
func (*WriteFailsafeConsumptionActivePowerLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{6}
}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type WriteFailsafeConsumptionActivePowerLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgCounter    uint64                 `protobuf:"varint,1,opt,name=msg_counter,json=msgCounter,proto3" json:"msg_counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFailsafeConsumptionActivePowerLimitResponse) Reset() {
	*x = WriteFailsafeConsumptionActivePowerLimitResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFailsafeConsumptionActivePowerLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFailsafeConsumptionActivePowerLimitResponse) ProtoMessage() {}

func (x *WriteFailsafeConsumptionActivePowerLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFailsafeConsumptionActivePowerLimitResponse.ProtoReflect.Descriptor instead.
func (*WriteFailsafeConsumptionActivePowerLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{7}
}

func (x *WriteFailsafeConsumptionActivePowerLimitResponse) GetMsgCounter() uint64 {
	if x != nil {
		return x.MsgCounter
	}
	return 0
}

type FailsafeDurationMinimumRequest struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FailsafeDurationMinimumRequest) Reset() {
	*x = FailsafeDurationMinimumRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeDurationMinimumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeDurationMinimumRequest) ProtoMessage() {}

func (x *FailsafeDurationMinimumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeDurationMinimumRequest.ProtoReflect.Descriptor instead.
func (*FailsafeDurationMinimumRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{8}
}

func (x *FailsafeDurationMinimumRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *FailsafeDurationMinimumRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

type FailsafeDurationMinimumResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DurationNanoseconds uint64                 `protobuf:"varint,1,opt,name=duration_nanoseconds,json=durationNanoseconds,proto3" json:"duration_nanoseconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FailsafeDurationMinimumResponse) Reset() {
	*x = FailsafeDurationMinimumResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeDurationMinimumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeDurationMinimumResponse) ProtoMessage() {}

func (x *FailsafeDurationMinimumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeDurationMinimumResponse.ProtoReflect.Descriptor instead.
func (*FailsafeDurationMinimumResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{9}
}

func (x *FailsafeDurationMinimumResponse) GetDurationNanoseconds() uint64 {
	if x != nil {
		return x.DurationNanoseconds
	}
	return 0
}

type WriteFailsafeDurationMinimumRequest struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	DurationNanoseconds uint64                      `protobuf:"varint,3,opt,name=duration_nanoseconds,json=durationNanoseconds,proto3" json:"duration_nanoseconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WriteFailsafeDurationMinimumRequest) Reset() {
	*x = WriteFailsafeDurationMinimumRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFailsafeDurationMinimumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFailsafeDurationMinimumRequest) ProtoMessage() {}

func (x *WriteFailsafeDurationMinimumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFailsafeDurationMinimumRequest.ProtoReflect.Descriptor instead.
func (*WriteFailsafeDurationMinimumRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{10}
}

func (x *WriteFailsafeDurationMinimumRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *WriteFailsafeDurationMinimumRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

func (x *WriteFailsafeDurationMinimumRequest) GetDurationNanoseconds() uint64 {
	if x != nil {
		return x.DurationNanoseconds
	}
	return 0
}

type WriteFailsafeDurationMinimumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgCounter    uint64                 `protobuf:"varint,1,opt,name=msg_counter,json=msgCounter,proto3" json:"msg_counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFailsafeDurationMinimumResponse) Reset() {
	*x = WriteFailsafeDurationMinimumResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFailsafeDurationMinimumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFailsafeDurationMinimumResponse) ProtoMessage() {}

func (x *WriteFailsafeDurationMinimumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFailsafeDurationMinimumResponse.ProtoReflect.Descriptor instead.
func (*WriteFailsafeDurationMinimumResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{11}
}

func (x *WriteFailsafeDurationMinimumResponse) GetMsgCounter() uint64 {
	if x != nil {
		return x.MsgCounter
	}
	return 0
}

type StartHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartHeartbeatRequest) Reset() {
	*x = StartHeartbeatRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHeartbeatRequest) ProtoMessage() {}

func (x *StartHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*StartHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{12}
}

type StartHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartHeartbeatResponse) Reset() {
	*x = StartHeartbeatResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHeartbeatResponse) ProtoMessage() {}

func (x *StartHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*StartHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{13}
}

type StopHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopHeartbeatRequest) Reset() {
	*x = StopHeartbeatRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopHeartbeatRequest) ProtoMessage() {}

func (x *StopHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*StopHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{14}
}

type StopHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopHeartbeatResponse) Reset() {
	*x = StopHeartbeatResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopHeartbeatResponse) ProtoMessage() {}

func (x *StopHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*StopHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{15}
}

type IsHeartbeatWithinDurationRequest struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IsHeartbeatWithinDurationRequest) Reset() {
	*x = IsHeartbeatWithinDurationRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHeartbeatWithinDurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHeartbeatWithinDurationRequest) ProtoMessage() {}

func (x *IsHeartbeatWithinDurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHeartbeatWithinDurationRequest.ProtoReflect.Descriptor instead.
func (*IsHeartbeatWithinDurationRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{16}
}

func (x *IsHeartbeatWithinDurationRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *IsHeartbeatWithinDurationRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

type IsHeartbeatWithinDurationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WithinDuration bool                   `protobuf:"varint,1,opt,name=within_duration,json=withinDuration,proto3" json:"within_duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IsHeartbeatWithinDurationResponse) Reset() {
	*x = IsHeartbeatWithinDurationResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHeartbeatWithinDurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHeartbeatWithinDurationResponse) ProtoMessage() {}

func (x *IsHeartbeatWithinDurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHeartbeatWithinDurationResponse.ProtoReflect.Descriptor instead.
func (*IsHeartbeatWithinDurationResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{17}
}

func (x *IsHeartbeatWithinDurationResponse) GetWithinDuration() bool {
	if x != nil {
		return x.WithinDuration
	}
	return false
}

type ConsumptionNominalMaxRequest struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConsumptionNominalMaxRequest) Reset() {
	*x = ConsumptionNominalMaxRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionNominalMaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionNominalMaxRequest) ProtoMessage() {}

func (x *ConsumptionNominalMaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionNominalMaxRequest.ProtoReflect.Descriptor instead.
func (*ConsumptionNominalMaxRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{18}
}

func (x *ConsumptionNominalMaxRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *ConsumptionNominalMaxRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

type ConsumptionNominalMaxResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ConsumptionNominalMax float64                `protobuf:"fixed64,1,opt,name=consumption_nominal_max,json=consumptionNominalMax,proto3" json:"consumption_nominal_max,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConsumptionNominalMaxResponse) Reset() {
	*x = ConsumptionNominalMaxResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionNominalMaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionNominalMaxResponse) ProtoMessage() {}

func (x *ConsumptionNominalMaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionNominalMaxResponse.ProtoReflect.Descriptor instead.
func (*ConsumptionNominalMaxResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{19}
}

func (x *ConsumptionNominalMaxResponse) GetConsumptionNominalMax() float64 {
	if x != nil {
		return x.ConsumptionNominalMax
	}
	return 0
}

var File_usecases_eg_lpc_messages_proto protoreflect.FileDescriptor

const file_usecases_eg_lpc_messages_proto_rawDesc = "" +
	"\n" +
	"\x1eusecases/eg/lpc/messages.proto\x12\x06eg_lpc\x1a\x18common_types/types.proto\"\x89\x01\n" +
	"\x17ConsumptionLimitRequest\x12\x1d\n" +
	"\n" +
	"remote_ski\x18\x01 \x01(\tR\tremoteSki\x12O\n" +
	"\x15remote_entity_address\x18\x02 \x01(\v2\x1b.common_types.EntityAddressR\x13remoteEntityAddress\"I\n" +
	"\x18ConsumptionLimitResponse\x12-\n" +
	"\x05limit\x18\x01 \x01(\v2\x17.common_types.LoadLimitR\x05limit\"\xbd\x01\n" +
	"\x1cWriteConsumptionLimitRequest\x12\x1d\n" +
	"\n" +
	"remote_ski\x18\x01 \x01(\tR\tremoteSki\x12O\n" +
	"\x15remote_entity_address\x18\x02 \x01(\v2\x1b.common_types.EntityAddressR\x13remoteEntityAddress\x12-\n" +
	"\x05limit\x18\x03 \x01(\v2\x17.common_types.LoadLimitR\x05limit\"\xb0\x01\n" +
	"\x1dWriteConsumptionLimitResponse\x12&\n" +
	"\ferror_number\x18\x01 \x01(\x04H\x00R\verrorNumber\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\vmsg_counter\x18\x03 \x01(\x04R\n" +
	"msgCounterB\x0f\n" +
	"\r_error_numberB\x0e\n" +
	"\f_description\"\x9c\x01\n" +
	"*FailsafeConsumptionActivePowerLimitRequest\x12\x1d\n" +
	"\n" +
	"remote_ski\x18\x01 \x01(\tR\tremoteSki\x12O\n" +
	"\x15remote_entity_address\x18\x02 \x01(\v2\x1b.common_types.EntityAddressR\x13remoteEntityAddress\"C\n" +
	"+FailsafeConsumptionActivePowerLimitResponse\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x01R\x05limit\"\xb7\x01\n" +
	"/WriteFailsafeConsumptionActivePowerLimitRequest\x12\x1d\n" +
	"\n" +
	"remote_ski\x18\x01 \x01(\tR\tremoteSki\x12O\n" +
	"\x15remote_entity_address\x18\x02 \x01(\v2\x1b.common_types.EntityAddressR\x13remoteEntityAddress\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x01R\x05limit\"S\n" +
	"0WriteFailsafeConsumptionActivePowerLimitResponse\x12\x1f\n" +
	"\vmsg_counter\x18\x01 \x01(\x04R\n" +
	"msgCounter\"\x90\x01\n" +
	"\x1eFailsafeDurationMinimumRequest\x12\x1d\n" +
	"\n" +
	"remote_ski\x18\x01 \x01(\tR\tremoteSki\x12O\n" +
	"\x15remote_entity_address\x18\x02 \x01(\v2\x1b.common_types.EntityAddressR\x13remoteEntityAddress\"T\n" +
	"\x1fFailsafeDurationMinimumResponse\x121\n" +
	"\x14duration_nanoseconds\x18\x01 \x01(\x04R\x13durationNanoseconds\"\xc8\x01\n" +
	"#WriteFailsafeDurationMinimumRequest\x12\x1d\n" +
	"\n" +
	"remote_ski\x18\x01 \x01(\tR\tremoteSki\x12O\n" +
	"\x15remote_entity_address\x18\x02 \x01(\v2\x1b.common_types.EntityAddressR\x13remoteEntityAddress\x121\n" +
	"\x14duration_nanoseconds\x18\x03 \x01(\x04R\x13durationNanoseconds\"G\n" +
	"$WriteFailsafeDurationMinimumResponse\x12\x1f\n" +
	"\vmsg_counter\x18\x01 \x01(\x04R\n" +
	"msgCounter\"\x17\n" +
	"\x15StartHeartbeatRequest\"\x18\n" +
	"\x16StartHeartbeatResponse\"\x16\n" +
	"\x14StopHeartbeatRequest\"\x17\n" +
	"\x15StopHeartbeatResponse\"\x92\x01\n" +
	" IsHeartbeatWithinDurationRequest\x12\x1d\n" +
	"\n" +
	"remote_ski\x18\x01 \x01(\tR\tremoteSki\x12O\n" +
	"\x15remote_entity_address\x18\x02 \x01(\v2\x1b.common_types.EntityAddressR\x13remoteEntityAddress\"L\n" +
	"!IsHeartbeatWithinDurationResponse\x12'\n" +
	"\x0fwithin_duration\x18\x01 \x01(\bR\x0ewithinDuration\"\x8e\x01\n" +
	"\x1cConsumptionNominalMaxRequest\x12\x1d\n" +
	"\n" +
	"remote_ski\x18\x01 \x01(\tR\tremoteSki\x12O\n" +
	"\x15remote_entity_address\x18\x02 \x01(\v2\x1b.common_types.EntityAddressR\x13remoteEntityAddress\"W\n" +
	"\x1dConsumptionNominalMaxResponse\x126\n" +
	"\x17consumption_nominal_max\x18\x01 \x01(\x01R\x15consumptionNominalMaxB=Z;github.com/enbility/eebus-grpc/rpc_services/usecases/eg/lpcb\x06proto3"

var (
	file_usecases_eg_lpc_messages_proto_rawDescOnce sync.Once
	file_usecases_eg_lpc_messages_proto_rawDescData []byte
)

func file_usecases_eg_lpc_messages_proto_rawDescGZIP() []byte {
	file_usecases_eg_lpc_messages_proto_rawDescOnce.Do(func() {
		file_usecases_eg_lpc_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usecases_eg_lpc_messages_proto_rawDesc), len(file_usecases_eg_lpc_messages_proto_rawDesc)))
	})
	return file_usecases_eg_lpc_messages_proto_rawDescData
}

var file_usecases_eg_lpc_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_usecases_eg_lpc_messages_proto_goTypes = []any{
	(*ConsumptionLimitRequest)(nil),                          // 0: eg_lpc.ConsumptionLimitRequest
	(*ConsumptionLimitResponse)(nil),                         // 1: eg_lpc.ConsumptionLimitResponse
	(*WriteConsumptionLimitRequest)(nil),                     // 2: eg_lpc.WriteConsumptionLimitRequest
	(*WriteConsumptionLimitResponse)(nil),                    // 3: eg_lpc.WriteConsumptionLimitResponse
	(*FailsafeConsumptionActivePowerLimitRequest)(nil),       // 4: eg_lpc.FailsafeConsumptionActivePowerLimitRequest
	(*FailsafeConsumptionActivePowerLimitResponse)(nil),      // 5: eg_lpc.FailsafeConsumptionActivePowerLimitResponse
	(*WriteFailsafeConsumptionActivePowerLimitRequest)(nil),  // 6: eg_lpc.WriteFailsafeConsumptionActivePowerLimitRequest
	(*WriteFailsafeConsumptionActivePowerLimitResponse)(nil), // 7: eg_lpc.WriteFailsafeConsumptionActivePowerLimitResponse
	(*FailsafeDurationMinimumRequest)(nil),                   // 8: eg_lpc.FailsafeDurationMinimumRequest
	(*FailsafeDurationMinimumResponse)(nil),                  // 9: eg_lpc.FailsafeDurationMinimumResponse
	(*WriteFailsafeDurationMinimumRequest)(nil),              // 10: eg_lpc.WriteFailsafeDurationMinimumRequest
	(*WriteFailsafeDurationMinimumResponse)(nil),             // 11: eg_lpc.WriteFailsafeDurationMinimumResponse
	(*StartHeartbeatRequest)(nil),                            // 12: eg_lpc.StartHeartbeatRequest
	(*StartHeartbeatResponse)(nil),                           // 13: eg_lpc.StartHeartbeatResponse
	(*StopHeartbeatRequest)(nil),                             // 14: eg_lpc.StopHeartbeatRequest
	(*StopHeartbeatResponse)(nil),                            // 15: eg_lpc.StopHeartbeatResponse
	(*IsHeartbeatWithinDurationRequest)(nil),                 // 16: eg_lpc.IsHeartbeatWithinDurationRequest
	(*IsHeartbeatWithinDurationResponse)(nil),                // 17: eg_lpc.IsHeartbeatWithinDurationResponse
	(*ConsumptionNominalMaxRequest)(nil),                     // 18: eg_lpc.ConsumptionNominalMaxRequest
	(*ConsumptionNominalMaxResponse)(nil),                    // 19: eg_lpc.ConsumptionNominalMaxResponse
	(*common_types.EntityAddress)(nil),                       // 20: common_types.EntityAddress
	(*common_types.LoadLimit)(nil),                           // 21: common_types.LoadLimit
}
var file_usecases_eg_lpc_messages_proto_depIdxs = []int32{
	20, // 0: eg_lpc.ConsumptionLimitRequest.remote_entity_address:type_name -> common_types.EntityAddress
	21, // 1: eg_lpc.ConsumptionLimitResponse.limit:type_name -> common_types.LoadLimit
	20, // 2: eg_lpc.WriteConsumptionLimitRequest.remote_entity_address:type_name -> common_types.EntityAddress
	21, // 3: eg_lpc.WriteConsumptionLimitRequest.limit:type_name -> common_types.LoadLimit
	20, // 4: eg_lpc.FailsafeConsumptionActivePowerLimitRequest.remote_entity_address:type_name -> common_types.EntityAddress
	20, // 5: eg_lpc.WriteFailsafeConsumptionActivePowerLimitRequest.remote_entity_address:type_name -> common_types.EntityAddress
	20, // 6: eg_lpc.FailsafeDurationMinimumRequest.remote_entity_address:type_name -> common_types.EntityAddress
	20, // 7: eg_lpc.WriteFailsafeDurationMinimumRequest.remote_entity_address:type_name -> common_types.EntityAddress
	20, // 8: eg_lpc.IsHeartbeatWithinDurationRequest.remote_entity_address:type_name -> common_types.EntityAddress
	20, // 9: eg_lpc.ConsumptionNominalMaxRequest.remote_entity_address:type_name -> common_types.EntityAddress
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_usecases_eg_lpc_messages_proto_init() }
func file_usecases_eg_lpc_messages_proto_init() {
	if File_usecases_eg_lpc_messages_proto != nil {
		return
	}
	file_usecases_eg_lpc_messages_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usecases_eg_lpc_messages_proto_rawDesc), len(file_usecases_eg_lpc_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_usecases_eg_lpc_messages_proto_goTypes,
		DependencyIndexes: file_usecases_eg_lpc_messages_proto_depIdxs,
		MessageInfos:      file_usecases_eg_lpc_messages_proto_msgTypes,
	}.Build()
	File_usecases_eg_lpc_messages_proto = out.File
	file_usecases_eg_lpc_messages_proto_goTypes = nil
	file_usecases_eg_lpc_messages_proto_depIdxs = nil
}
