// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: usecases/eg/lpc/service.proto

package lpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_usecases_eg_lpc_service_proto protoreflect.FileDescriptor

const file_usecases_eg_lpc_service_proto_rawDesc = "" +
	"\n" +
	"\x1dusecases/eg/lpc/service.proto\x12\x06eg_lpc\x1a\x1eusecases/eg/lpc/messages.proto2\xf7\b\n" +
	"\x15EnergyGuardLPCControl\x12W\n" +
	"\x10ConsumptionLimit\x12\x1f.eg_lpc.ConsumptionLimitRequest\x1a .eg_lpc.ConsumptionLimitResponse\"\x00\x12f\n" +
	"\x15WriteConsumptionLimit\x12$.eg_lpc.WriteConsumptionLimitRequest\x1a%.eg_lpc.WriteConsumptionLimitResponse\"\x00\x12\x90\x01\n" +
	"#FailsafeConsumptionActivePowerLimit\x122.eg_lpc.FailsafeConsumptionActivePowerLimitRequest\x1a3.eg_lpc.FailsafeConsumptionActivePowerLimitResponse\"\x00\x12\x9f\x01\n" +
	"(WriteFailsafeConsumptionActivePowerLimit\x127.eg_lpc.WriteFailsafeConsumptionActivePowerLimitRequest\x1a8.eg_lpc.WriteFailsafeConsumptionActivePowerLimitResponse\"\x00\x12l\n" +
	"\x17FailsafeDurationMinimum\x12&.eg_lpc.FailsafeDurationMinimumRequest\x1a'.eg_lpc.FailsafeDurationMinimumResponse\"\x00\x12{\n" +
	"\x1cWriteFailsafeDurationMinimum\x12+.eg_lpc.WriteFailsafeDurationMinimumRequest\x1a,.eg_lpc.WriteFailsafeDurationMinimumResponse\"\x00\x12Q\n" +
	"\x0eStartHeartbeat\x12\x1d.eg_lpc.StartHeartbeatRequest\x1a\x1e.eg_lpc.StartHeartbeatResponse\"\x00\x12N\n" +
	"\rStopHeartbeat\x12\x1c.eg_lpc.StopHeartbeatRequest\x1a\x1d.eg_lpc.StopHeartbeatResponse\"\x00\x12r\n" +
	"\x19IsHeartbeatWithinDuration\x12(.eg_lpc.IsHeartbeatWithinDurationRequest\x1a).eg_lpc.IsHeartbeatWithinDurationResponse\"\x00\x12f\n" +
	"\x15ConsumptionNominalMax\x12$.eg_lpc.ConsumptionNominalMaxRequest\x1a%.eg_lpc.ConsumptionNominalMaxResponse\"\x00B=Z;github.com/enbility/eebus-grpc/rpc_services/usecases/eg/lpcb\x06proto3"

var file_usecases_eg_lpc_service_proto_goTypes = []any{
	(*ConsumptionLimitRequest)(nil),                          // 0: eg_lpc.ConsumptionLimitRequest
	(*WriteConsumptionLimitRequest)(nil),                     // 1: eg_lpc.WriteConsumptionLimitRequest
	(*FailsafeConsumptionActivePowerLimitRequest)(nil),       // 2: eg_lpc.FailsafeConsumptionActivePowerLimitRequest
	(*WriteFailsafeConsumptionActivePowerLimitRequest)(nil),  // 3: eg_lpc.WriteFailsafeConsumptionActivePowerLimitRequest
	(*FailsafeDurationMinimumRequest)(nil),                   // 4: eg_lpc.FailsafeDurationMinimumRequest
	(*WriteFailsafeDurationMinimumRequest)(nil),              // 5: eg_lpc.WriteFailsafeDurationMinimumRequest
	(*StartHeartbeatRequest)(nil),                            // 6: eg_lpc.StartHeartbeatRequest
	(*StopHeartbeatRequest)(nil),                             // 7: eg_lpc.StopHeartbeatRequest
	(*IsHeartbeatWithinDurationRequest)(nil),                 // 8: eg_lpc.IsHeartbeatWithinDurationRequest
	(*ConsumptionNominalMaxRequest)(nil),                     // 9: eg_lpc.ConsumptionNominalMaxRequest
	(*ConsumptionLimitResponse)(nil),                         // 10: eg_lpc.ConsumptionLimitResponse
	(*WriteConsumptionLimitResponse)(nil),                    // 11: eg_lpc.WriteConsumptionLimitResponse
	(*FailsafeConsumptionActivePowerLimitResponse)(nil),      // 12: eg_lpc.FailsafeConsumptionActivePowerLimitResponse
	(*WriteFailsafeConsumptionActivePowerLimitResponse)(nil), // 13: eg_lpc.WriteFailsafeConsumptionActivePowerLimitResponse
	(*FailsafeDurationMinimumResponse)(nil),                  // 14: eg_lpc.FailsafeDurationMinimumResponse
	(*WriteFailsafeDurationMinimumResponse)(nil),             // 15: eg_lpc.WriteFailsafeDurationMinimumResponse
	(*StartHeartbeatResponse)(nil),                           // 16: eg_lpc.StartHeartbeatResponse
	(*StopHeartbeatResponse)(nil),                            // 17: eg_lpc.StopHeartbeatResponse
	(*IsHeartbeatWithinDurationResponse)(nil),                // 18: eg_lpc.IsHeartbeatWithinDurationResponse
	(*ConsumptionNominalMaxResponse)(nil),                    // 19: eg_lpc.ConsumptionNominalMaxResponse
}
var file_usecases_eg_lpc_service_proto_depIdxs = []int32{
	0,  // 0: eg_lpc.EnergyGuardLPCControl.ConsumptionLimit:input_type -> eg_lpc.ConsumptionLimitRequest
	1,  // 1: eg_lpc.EnergyGuardLPCControl.WriteConsumptionLimit:input_type -> eg_lpc.WriteConsumptionLimitRequest
	2,  // 2: eg_lpc.EnergyGuardLPCControl.FailsafeConsumptionActivePowerLimit:input_type -> eg_lpc.FailsafeConsumptionActivePowerLimitRequest
	3,  // 3: eg_lpc.EnergyGuardLPCControl.WriteFailsafeConsumptionActivePowerLimit:input_type -> eg_lpc.WriteFailsafeConsumptionActivePowerLimitRequest
	4,  // 4: eg_lpc.EnergyGuardLPCControl.FailsafeDurationMinimum:input_type -> eg_lpc.FailsafeDurationMinimumRequest
	5,  // 5: eg_lpc.EnergyGuardLPCControl.WriteFailsafeDurationMinimum:input_type -> eg_lpc.WriteFailsafeDurationMinimumRequest
	6,  // 6: eg_lpc.EnergyGuardLPCControl.StartHeartbeat:input_type -> eg_lpc.StartHeartbeatRequest
	7,  // 7: eg_lpc.EnergyGuardLPCControl.StopHeartbeat:input_type -> eg_lpc.StopHeartbeatRequest
	8,  // 8: eg_lpc.EnergyGuardLPCControl.IsHeartbeatWithinDuration:input_type -> eg_lpc.IsHeartbeatWithinDurationRequest
	9,  // 9: eg_lpc.EnergyGuardLPCControl.ConsumptionNominalMax:input_type -> eg_lpc.ConsumptionNominalMaxRequest
	10, // 10: eg_lpc.EnergyGuardLPCControl.ConsumptionLimit:output_type -> eg_lpc.ConsumptionLimitResponse
	11, // 11: eg_lpc.EnergyGuardLPCControl.WriteConsumptionLimit:output_type -> eg_lpc.WriteConsumptionLimitResponse
	12, // 12: eg_lpc.EnergyGuardLPCControl.FailsafeConsumptionActivePowerLimit:output_type -> eg_lpc.FailsafeConsumptionActivePowerLimitResponse
	13, // 13: eg_lpc.EnergyGuardLPCControl.WriteFailsafeConsumptionActivePowerLimit:output_type -> eg_lpc.WriteFailsafeConsumptionActivePowerLimitResponse
	14, // 14: eg_lpc.EnergyGuardLPCControl.FailsafeDurationMinimum:output_type -> eg_lpc.FailsafeDurationMinimumResponse
	15, // 15: eg_lpc.EnergyGuardLPCControl.WriteFailsafeDurationMinimum:output_type -> eg_lpc.WriteFailsafeDurationMinimumResponse
	16, // 16: eg_lpc.EnergyGuardLPCControl.StartHeartbeat:output_type -> eg_lpc.StartHeartbeatResponse
	17, // 17: eg_lpc.EnergyGuardLPCControl.StopHeartbeat:output_type -> eg_lpc.StopHeartbeatResponse
	18, // 18: eg_lpc.EnergyGuardLPCControl.IsHeartbeatWithinDuration:output_type -> eg_lpc.IsHeartbeatWithinDurationResponse
	19, // 19: eg_lpc.EnergyGuardLPCControl.ConsumptionNominalMax:output_type -> eg_lpc.ConsumptionNominalMaxResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_usecases_eg_lpc_service_proto_init() }
func file_usecases_eg_lpc_service_proto_init() {
	if File_usecases_eg_lpc_service_proto != nil {
		return
	}
	file_usecases_eg_lpc_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usecases_eg_lpc_service_proto_rawDesc), len(file_usecases_eg_lpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usecases_eg_lpc_service_proto_goTypes,
		DependencyIndexes: file_usecases_eg_lpc_service_proto_depIdxs,
	}.Build()
	File_usecases_eg_lpc_service_proto = out.File
	file_usecases_eg_lpc_service_proto_goTypes = nil
	file_usecases_eg_lpc_service_proto_depIdxs = nil
}
