// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: usecases/cs/lpc/service.proto

package lpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_usecases_cs_lpc_service_proto protoreflect.FileDescriptor

const file_usecases_cs_lpc_service_proto_rawDesc = "" +
	"\n" +
	"\x1dusecases/cs/lpc/service.proto\x12\x06cs_lpc\x1a\x1eusecases/cs/lpc/messages.proto2\xcb\v\n" +
	"\x1cControllableSystemLPCControl\x12W\n" +
	"\x10ConsumptionLimit\x12\x1f.cs_lpc.ConsumptionLimitRequest\x1a .cs_lpc.ConsumptionLimitResponse\"\x00\x12`\n" +
	"\x13SetConsumptionLimit\x12\".cs_lpc.SetConsumptionLimitRequest\x1a#.cs_lpc.SetConsumptionLimitResponse\"\x00\x12l\n" +
	"\x17PendingConsumptionLimit\x12&.cs_lpc.PendingConsumptionLimitRequest\x1a'.cs_lpc.PendingConsumptionLimitResponse\"\x00\x12~\n" +
	"\x1dApproveOrDenyConsumptionLimit\x12,.cs_lpc.ApproveOrDenyConsumptionLimitRequest\x1a-.cs_lpc.ApproveOrDenyConsumptionLimitResponse\"\x00\x12\x90\x01\n" +
	"#FailsafeConsumptionActivePowerLimit\x122.cs_lpc.FailsafeConsumptionActivePowerLimitRequest\x1a3.cs_lpc.FailsafeConsumptionActivePowerLimitResponse\"\x00\x12\x99\x01\n" +
	"&SetFailsafeConsumptionActivePowerLimit\x125.cs_lpc.SetFailsafeConsumptionActivePowerLimitRequest\x1a6.cs_lpc.SetFailsafeConsumptionActivePowerLimitResponse\"\x00\x12l\n" +
	"\x17FailsafeDurationMinimum\x12&.cs_lpc.FailsafeDurationMinimumRequest\x1a'.cs_lpc.FailsafeDurationMinimumResponse\"\x00\x12u\n" +
	"\x1aSetFailsafeDurationMinimum\x12).cs_lpc.SetFailsafeDurationMinimumRequest\x1a*.cs_lpc.SetFailsafeDurationMinimumResponse\"\x00\x12Q\n" +
	"\x0eStartHeartbeat\x12\x1d.cs_lpc.StartHeartbeatRequest\x1a\x1e.cs_lpc.StartHeartbeatResponse\"\x00\x12N\n" +
	"\rStopHeartbeat\x12\x1c.cs_lpc.StopHeartbeatRequest\x1a\x1d.cs_lpc.StopHeartbeatResponse\"\x00\x12r\n" +
	"\x19IsHeartbeatWithinDuration\x12(.cs_lpc.IsHeartbeatWithinDurationRequest\x1a).cs_lpc.IsHeartbeatWithinDurationResponse\"\x00\x12f\n" +
	"\x15ConsumptionNominalMax\x12$.cs_lpc.ConsumptionNominalMaxRequest\x1a%.cs_lpc.ConsumptionNominalMaxResponse\"\x00\x12o\n" +
	"\x18SetConsumptionNominalMax\x12'.cs_lpc.SetConsumptionNominalMaxRequest\x1a(.cs_lpc.SetConsumptionNominalMaxResponse\"\x00B=Z;github.com/enbility/eebus-grpc/rpc_services/usecases/cs/lpcb\x06proto3"

var file_usecases_cs_lpc_service_proto_goTypes = []any{
	(*ConsumptionLimitRequest)(nil),                        // 0: cs_lpc.ConsumptionLimitRequest
	(*SetConsumptionLimitRequest)(nil),                     // 1: cs_lpc.SetConsumptionLimitRequest
	(*PendingConsumptionLimitRequest)(nil),                 // 2: cs_lpc.PendingConsumptionLimitRequest
	(*ApproveOrDenyConsumptionLimitRequest)(nil),           // 3: cs_lpc.ApproveOrDenyConsumptionLimitRequest
	(*FailsafeConsumptionActivePowerLimitRequest)(nil),     // 4: cs_lpc.FailsafeConsumptionActivePowerLimitRequest
	(*SetFailsafeConsumptionActivePowerLimitRequest)(nil),  // 5: cs_lpc.SetFailsafeConsumptionActivePowerLimitRequest
	(*FailsafeDurationMinimumRequest)(nil),                 // 6: cs_lpc.FailsafeDurationMinimumRequest
	(*SetFailsafeDurationMinimumRequest)(nil),              // 7: cs_lpc.SetFailsafeDurationMinimumRequest
	(*StartHeartbeatRequest)(nil),                          // 8: cs_lpc.StartHeartbeatRequest
	(*StopHeartbeatRequest)(nil),                           // 9: cs_lpc.StopHeartbeatRequest
	(*IsHeartbeatWithinDurationRequest)(nil),               // 10: cs_lpc.IsHeartbeatWithinDurationRequest
	(*ConsumptionNominalMaxRequest)(nil),                   // 11: cs_lpc.ConsumptionNominalMaxRequest
	(*SetConsumptionNominalMaxRequest)(nil),                // 12: cs_lpc.SetConsumptionNominalMaxRequest
	(*ConsumptionLimitResponse)(nil),                       // 13: cs_lpc.ConsumptionLimitResponse
	(*SetConsumptionLimitResponse)(nil),                    // 14: cs_lpc.SetConsumptionLimitResponse
	(*PendingConsumptionLimitResponse)(nil),                // 15: cs_lpc.PendingConsumptionLimitResponse
	(*ApproveOrDenyConsumptionLimitResponse)(nil),          // 16: cs_lpc.ApproveOrDenyConsumptionLimitResponse
	(*FailsafeConsumptionActivePowerLimitResponse)(nil),    // 17: cs_lpc.FailsafeConsumptionActivePowerLimitResponse
	(*SetFailsafeConsumptionActivePowerLimitResponse)(nil), // 18: cs_lpc.SetFailsafeConsumptionActivePowerLimitResponse
	(*FailsafeDurationMinimumResponse)(nil),                // 19: cs_lpc.FailsafeDurationMinimumResponse
	(*SetFailsafeDurationMinimumResponse)(nil),             // 20: cs_lpc.SetFailsafeDurationMinimumResponse
	(*StartHeartbeatResponse)(nil),                         // 21: cs_lpc.StartHeartbeatResponse
	(*StopHeartbeatResponse)(nil),                          // 22: cs_lpc.StopHeartbeatResponse
	(*IsHeartbeatWithinDurationResponse)(nil),              // 23: cs_lpc.IsHeartbeatWithinDurationResponse
	(*ConsumptionNominalMaxResponse)(nil),                  // 24: cs_lpc.ConsumptionNominalMaxResponse
	(*SetConsumptionNominalMaxResponse)(nil),               // 25: cs_lpc.SetConsumptionNominalMaxResponse
}
var file_usecases_cs_lpc_service_proto_depIdxs = []int32{
	0,  // 0: cs_lpc.ControllableSystemLPCControl.ConsumptionLimit:input_type -> cs_lpc.ConsumptionLimitRequest
	1,  // 1: cs_lpc.ControllableSystemLPCControl.SetConsumptionLimit:input_type -> cs_lpc.SetConsumptionLimitRequest
	2,  // 2: cs_lpc.ControllableSystemLPCControl.PendingConsumptionLimit:input_type -> cs_lpc.PendingConsumptionLimitRequest
	3,  // 3: cs_lpc.ControllableSystemLPCControl.ApproveOrDenyConsumptionLimit:input_type -> cs_lpc.ApproveOrDenyConsumptionLimitRequest
	4,  // 4: cs_lpc.ControllableSystemLPCControl.FailsafeConsumptionActivePowerLimit:input_type -> cs_lpc.FailsafeConsumptionActivePowerLimitRequest
	5,  // 5: cs_lpc.ControllableSystemLPCControl.SetFailsafeConsumptionActivePowerLimit:input_type -> cs_lpc.SetFailsafeConsumptionActivePowerLimitRequest
	6,  // 6: cs_lpc.ControllableSystemLPCControl.FailsafeDurationMinimum:input_type -> cs_lpc.FailsafeDurationMinimumRequest
	7,  // 7: cs_lpc.ControllableSystemLPCControl.SetFailsafeDurationMinimum:input_type -> cs_lpc.SetFailsafeDurationMinimumRequest
	8,  // 8: cs_lpc.ControllableSystemLPCControl.StartHeartbeat:input_type -> cs_lpc.StartHeartbeatRequest
	9,  // 9: cs_lpc.ControllableSystemLPCControl.StopHeartbeat:input_type -> cs_lpc.StopHeartbeatRequest
	10, // 10: cs_lpc.ControllableSystemLPCControl.IsHeartbeatWithinDuration:input_type -> cs_lpc.IsHeartbeatWithinDurationRequest
	11, // 11: cs_lpc.ControllableSystemLPCControl.ConsumptionNominalMax:input_type -> cs_lpc.ConsumptionNominalMaxRequest
	12, // 12: cs_lpc.ControllableSystemLPCControl.SetConsumptionNominalMax:input_type -> cs_lpc.SetConsumptionNominalMaxRequest
	13, // 13: cs_lpc.ControllableSystemLPCControl.ConsumptionLimit:output_type -> cs_lpc.ConsumptionLimitResponse
	14, // 14: cs_lpc.ControllableSystemLPCControl.SetConsumptionLimit:output_type -> cs_lpc.SetConsumptionLimitResponse
	15, // 15: cs_lpc.ControllableSystemLPCControl.PendingConsumptionLimit:output_type -> cs_lpc.PendingConsumptionLimitResponse
	16, // 16: cs_lpc.ControllableSystemLPCControl.ApproveOrDenyConsumptionLimit:output_type -> cs_lpc.ApproveOrDenyConsumptionLimitResponse
	17, // 17: cs_lpc.ControllableSystemLPCControl.FailsafeConsumptionActivePowerLimit:output_type -> cs_lpc.FailsafeConsumptionActivePowerLimitResponse
	18, // 18: cs_lpc.ControllableSystemLPCControl.SetFailsafeConsumptionActivePowerLimit:output_type -> cs_lpc.SetFailsafeConsumptionActivePowerLimitResponse
	19, // 19: cs_lpc.ControllableSystemLPCControl.FailsafeDurationMinimum:output_type -> cs_lpc.FailsafeDurationMinimumResponse
	20, // 20: cs_lpc.ControllableSystemLPCControl.SetFailsafeDurationMinimum:output_type -> cs_lpc.SetFailsafeDurationMinimumResponse
	21, // 21: cs_lpc.ControllableSystemLPCControl.StartHeartbeat:output_type -> cs_lpc.StartHeartbeatResponse
	22, // 22: cs_lpc.ControllableSystemLPCControl.StopHeartbeat:output_type -> cs_lpc.StopHeartbeatResponse
	23, // 23: cs_lpc.ControllableSystemLPCControl.IsHeartbeatWithinDuration:output_type -> cs_lpc.IsHeartbeatWithinDurationResponse
	24, // 24: cs_lpc.ControllableSystemLPCControl.ConsumptionNominalMax:output_type -> cs_lpc.ConsumptionNominalMaxResponse
	25, // 25: cs_lpc.ControllableSystemLPCControl.SetConsumptionNominalMax:output_type -> cs_lpc.SetConsumptionNominalMaxResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_usecases_cs_lpc_service_proto_init() }
func file_usecases_cs_lpc_service_proto_init() {
	if File_usecases_cs_lpc_service_proto != nil {
		return
	}
	file_usecases_cs_lpc_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usecases_cs_lpc_service_proto_rawDesc), len(file_usecases_cs_lpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usecases_cs_lpc_service_proto_goTypes,
		DependencyIndexes: file_usecases_cs_lpc_service_proto_depIdxs,
	}.Build()
	File_usecases_cs_lpc_service_proto = out.File
	file_usecases_cs_lpc_service_proto_goTypes = nil
	file_usecases_cs_lpc_service_proto_depIdxs = nil
}
