// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: common_types/types.proto

package common_types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadLimit struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DurationNanoseconds int64                  `protobuf:"varint,1,opt,name=duration_nanoseconds,json=durationNanoseconds,proto3" json:"duration_nanoseconds,omitempty"`
	IsChangeable        bool                   `protobuf:"varint,2,opt,name=is_changeable,json=isChangeable,proto3" json:"is_changeable,omitempty"`
	IsActive            bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Value               float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	DeleteDuration      bool                   `protobuf:"varint,5,opt,name=delete_duration,json=deleteDuration,proto3" json:"delete_duration,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoadLimit) Reset() {
	*x = LoadLimit{}
	mi := &file_common_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadLimit) ProtoMessage() {}

func (x *LoadLimit) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadLimit.ProtoReflect.Descriptor instead.
func (*LoadLimit) Descriptor() ([]byte, []int) {
	return file_common_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *LoadLimit) GetDurationNanoseconds() int64 {
	if x != nil {
		return x.DurationNanoseconds
	}
	return 0
}

func (x *LoadLimit) GetIsChangeable() bool {
	if x != nil {
		return x.IsChangeable
	}
	return false
}

func (x *LoadLimit) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *LoadLimit) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *LoadLimit) GetDeleteDuration() bool {
	if x != nil {
		return x.DeleteDuration
	}
	return false
}

type EntityAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityAddress []uint32               `protobuf:"varint,1,rep,packed,name=entity_address,json=entityAddress,proto3" json:"entity_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityAddress) Reset() {
	*x = EntityAddress{}
	mi := &file_common_types_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityAddress) ProtoMessage() {}

func (x *EntityAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityAddress.ProtoReflect.Descriptor instead.
func (*EntityAddress) Descriptor() ([]byte, []int) {
	return file_common_types_types_proto_rawDescGZIP(), []int{1}
}

func (x *EntityAddress) GetEntityAddress() []uint32 {
	if x != nil {
		return x.EntityAddress
	}
	return nil
}

var File_common_types_types_proto protoreflect.FileDescriptor

const file_common_types_types_proto_rawDesc = "" +
	"\n" +
	"\x18common_types/types.proto\x12\fcommon_types\"\xbf\x01\n" +
	"\tLoadLimit\x121\n" +
	"\x14duration_nanoseconds\x18\x01 \x01(\x03R\x13durationNanoseconds\x12#\n" +
	"\ris_changeable\x18\x02 \x01(\bR\fisChangeable\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12'\n" +
	"\x0fdelete_duration\x18\x05 \x01(\bR\x0edeleteDuration\"6\n" +
	"\rEntityAddress\x12%\n" +
	"\x0eentity_address\x18\x01 \x03(\rR\rentityAddressB:Z8github.com/enbility/eebus-grpc/rpc_services/common_typesb\x06proto3"

var (
	file_common_types_types_proto_rawDescOnce sync.Once
	file_common_types_types_proto_rawDescData []byte
)

func file_common_types_types_proto_rawDescGZIP() []byte {
	file_common_types_types_proto_rawDescOnce.Do(func() {
		file_common_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_types_proto_rawDesc), len(file_common_types_types_proto_rawDesc)))
	})
	return file_common_types_types_proto_rawDescData
}

var file_common_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_types_types_proto_goTypes = []any{
	(*LoadLimit)(nil),     // 0: common_types.LoadLimit
	(*EntityAddress)(nil), // 1: common_types.EntityAddress
}
var file_common_types_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_types_types_proto_init() }
func file_common_types_types_proto_init() {
	if File_common_types_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_types_proto_rawDesc), len(file_common_types_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_types_proto_goTypes,
		DependencyIndexes: file_common_types_types_proto_depIdxs,
		MessageInfos:      file_common_types_types_proto_msgTypes,
	}.Build()
	File_common_types_types_proto = out.File
	file_common_types_types_proto_goTypes = nil
	file_common_types_types_proto_depIdxs = nil
}
