// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: control_service/control_service.proto

package control_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_control_service_control_service_proto protoreflect.FileDescriptor

const file_control_service_control_service_proto_rawDesc = "" +
	"\n" +
	"%control_service/control_service.proto\x12\x0fcontrol_service\x1a\x1econtrol_service/messages.proto2\xa9\a\n" +
	"\x0eControlService\x12O\n" +
	"\fStartService\x12\x1d.control_service.EmptyRequest\x1a\x1e.control_service.EmptyResponse\"\x00\x12N\n" +
	"\vStopService\x12\x1d.control_service.EmptyRequest\x1a\x1e.control_service.EmptyResponse\"\x00\x12P\n" +
	"\tSetConfig\x12!.control_service.SetConfigRequest\x1a\x1e.control_service.EmptyResponse\"\x00\x12M\n" +
	"\n" +
	"StartSetup\x12\x1d.control_service.EmptyRequest\x1a\x1e.control_service.EmptyResponse\"\x00\x12P\n" +
	"\tAddEntity\x12!.control_service.AddEntityRequest\x1a\x1e.control_service.EmptyResponse\"\x00\x12V\n" +
	"\fRemoveEntity\x12$.control_service.RemoveEntityRequest\x1a\x1e.control_service.EmptyResponse\"\x00\x12`\n" +
	"\x11RegisterRemoteSki\x12).control_service.RegisterRemoteSkiRequest\x1a\x1e.control_service.EmptyResponse\"\x00\x12W\n" +
	"\n" +
	"AddUseCase\x12\".control_service.AddUseCaseRequest\x1a#.control_service.AddUseCaseResponse\"\x00\x12}\n" +
	"\x16SubscribeUseCaseEvents\x12..control_service.SubscribeUseCaseEventsRequest\x1a/.control_service.SubscribeUseCaseEventsResponse\"\x000\x01\x12q\n" +
	"\x18SubscribeDiscoveryEvents\x120.control_service.SubscribeDiscoveryEventsRequest\x1a\x1f.control_service.DiscoveryEvent\"\x000\x01B=Z;github.com/enbility/eebus-grpc/rpc_services/control_serviceb\x06proto3"

var file_control_service_control_service_proto_goTypes = []any{
	(*EmptyRequest)(nil),                    // 0: control_service.EmptyRequest
	(*SetConfigRequest)(nil),                // 1: control_service.SetConfigRequest
	(*AddEntityRequest)(nil),                // 2: control_service.AddEntityRequest
	(*RemoveEntityRequest)(nil),             // 3: control_service.RemoveEntityRequest
	(*RegisterRemoteSkiRequest)(nil),        // 4: control_service.RegisterRemoteSkiRequest
	(*AddUseCaseRequest)(nil),               // 5: control_service.AddUseCaseRequest
	(*SubscribeUseCaseEventsRequest)(nil),   // 6: control_service.SubscribeUseCaseEventsRequest
	(*SubscribeDiscoveryEventsRequest)(nil), // 7: control_service.SubscribeDiscoveryEventsRequest
	(*EmptyResponse)(nil),                   // 8: control_service.EmptyResponse
	(*AddUseCaseResponse)(nil),              // 9: control_service.AddUseCaseResponse
	(*SubscribeUseCaseEventsResponse)(nil),  // 10: control_service.SubscribeUseCaseEventsResponse
	(*DiscoveryEvent)(nil),                  // 11: control_service.DiscoveryEvent
}
var file_control_service_control_service_proto_depIdxs = []int32{
	0,  // 0: control_service.ControlService.StartService:input_type -> control_service.EmptyRequest
	0,  // 1: control_service.ControlService.StopService:input_type -> control_service.EmptyRequest
	1,  // 2: control_service.ControlService.SetConfig:input_type -> control_service.SetConfigRequest
	0,  // 3: control_service.ControlService.StartSetup:input_type -> control_service.EmptyRequest
	2,  // 4: control_service.ControlService.AddEntity:input_type -> control_service.AddEntityRequest
	3,  // 5: control_service.ControlService.RemoveEntity:input_type -> control_service.RemoveEntityRequest
	4,  // 6: control_service.ControlService.RegisterRemoteSki:input_type -> control_service.RegisterRemoteSkiRequest
	5,  // 7: control_service.ControlService.AddUseCase:input_type -> control_service.AddUseCaseRequest
	6,  // 8: control_service.ControlService.SubscribeUseCaseEvents:input_type -> control_service.SubscribeUseCaseEventsRequest
	7,  // 9: control_service.ControlService.SubscribeDiscoveryEvents:input_type -> control_service.SubscribeDiscoveryEventsRequest
	8,  // 10: control_service.ControlService.StartService:output_type -> control_service.EmptyResponse
	8,  // 11: control_service.ControlService.StopService:output_type -> control_service.EmptyResponse
	8,  // 12: control_service.ControlService.SetConfig:output_type -> control_service.EmptyResponse
	8,  // 13: control_service.ControlService.StartSetup:output_type -> control_service.EmptyResponse
	8,  // 14: control_service.ControlService.AddEntity:output_type -> control_service.EmptyResponse
	8,  // 15: control_service.ControlService.RemoveEntity:output_type -> control_service.EmptyResponse
	8,  // 16: control_service.ControlService.RegisterRemoteSki:output_type -> control_service.EmptyResponse
	9,  // 17: control_service.ControlService.AddUseCase:output_type -> control_service.AddUseCaseResponse
	10, // 18: control_service.ControlService.SubscribeUseCaseEvents:output_type -> control_service.SubscribeUseCaseEventsResponse
	11, // 19: control_service.ControlService.SubscribeDiscoveryEvents:output_type -> control_service.DiscoveryEvent
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_control_service_control_service_proto_init() }
func file_control_service_control_service_proto_init() {
	if File_control_service_control_service_proto != nil {
		return
	}
	file_control_service_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_service_control_service_proto_rawDesc), len(file_control_service_control_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_service_control_service_proto_goTypes,
		DependencyIndexes: file_control_service_control_service_proto_depIdxs,
	}.Build()
	File_control_service_control_service_proto = out.File
	file_control_service_control_service_proto_goTypes = nil
	file_control_service_control_service_proto_depIdxs = nil
}
