// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: control_service/messages.proto

package control_service

import (
	common_types "github.com/enbility/eebus-grpc/rpc_services/common_types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoveryEvent_Type int32

const (
	DiscoveryEvent_UNKNOWN    DiscoveryEvent_Type = 0
	DiscoveryEvent_DISCOVERED DiscoveryEvent_Type = 1
	DiscoveryEvent_REMOVED    DiscoveryEvent_Type = 2
)

// Enum value maps for DiscoveryEvent_Type.
var (
	DiscoveryEvent_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "DISCOVERED",
		2: "REMOVED",
	}
	DiscoveryEvent_Type_value = map[string]int32{
		"UNKNOWN":    0,
		"DISCOVERED": 1,
		"REMOVED":    2,
	}
)

func (x DiscoveryEvent_Type) Enum() *DiscoveryEvent_Type {
	p := new(DiscoveryEvent_Type)
	*p = x
	return p
}

func (x DiscoveryEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoveryEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_control_service_messages_proto_enumTypes[0].Descriptor()
}

func (DiscoveryEvent_Type) Type() protoreflect.EnumType {
	return &file_control_service_messages_proto_enumTypes[0]
}

func (x DiscoveryEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoveryEvent_Type.Descriptor instead.
func (DiscoveryEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{11, 0}
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_control_service_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_control_service_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{1}
}

type SetConfigRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Port                    uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	VendorCode              string                 `protobuf:"bytes,2,opt,name=vendor_code,json=vendorCode,proto3" json:"vendor_code,omitempty"`
	DeviceBrand             string                 `protobuf:"bytes,3,opt,name=device_brand,json=deviceBrand,proto3" json:"device_brand,omitempty"`
	DeviceModel             string                 `protobuf:"bytes,4,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	SerialNumber            string                 `protobuf:"bytes,5,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	DeviceCategories        []DeviceCategory_Enum  `protobuf:"varint,6,rep,packed,name=device_categories,json=deviceCategories,proto3,enum=control_service.DeviceCategory_Enum" json:"device_categories,omitempty"`
	DeviceType              DeviceType_Enum        `protobuf:"varint,7,opt,name=device_type,json=deviceType,proto3,enum=control_service.DeviceType_Enum" json:"device_type,omitempty"`
	EntityTypes             []EntityType_Enum      `protobuf:"varint,8,rep,packed,name=entity_types,json=entityTypes,proto3,enum=control_service.EntityType_Enum" json:"entity_types,omitempty"`
	HeartbeatTimeoutSeconds uint32                 `protobuf:"varint,9,opt,name=heartbeat_timeout_seconds,json=heartbeatTimeoutSeconds,proto3" json:"heartbeat_timeout_seconds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_control_service_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SetConfigRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SetConfigRequest) GetVendorCode() string {
	if x != nil {
		return x.VendorCode
	}
	return ""
}

func (x *SetConfigRequest) GetDeviceBrand() string {
	if x != nil {
		return x.DeviceBrand
	}
	return ""
}

func (x *SetConfigRequest) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *SetConfigRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *SetConfigRequest) GetDeviceCategories() []DeviceCategory_Enum {
	if x != nil {
		return x.DeviceCategories
	}
	return nil
}

func (x *SetConfigRequest) GetDeviceType() DeviceType_Enum {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_UNKNOWN
}

func (x *SetConfigRequest) GetEntityTypes() []EntityType_Enum {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

func (x *SetConfigRequest) GetHeartbeatTimeoutSeconds() uint32 {
	if x != nil {
		return x.HeartbeatTimeoutSeconds
	}
	return 0
}

type AddEntityRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          EntityType_Enum             `protobuf:"varint,1,opt,name=type,proto3,enum=control_service.EntityType_Enum" json:"type,omitempty"`
	Address       *common_types.EntityAddress `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEntityRequest) Reset() {
	*x = AddEntityRequest{}
	mi := &file_control_service_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEntityRequest) ProtoMessage() {}

func (x *AddEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEntityRequest.ProtoReflect.Descriptor instead.
func (*AddEntityRequest) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{3}
}

func (x *AddEntityRequest) GetType() EntityType_Enum {
	if x != nil {
		return x.Type
	}
	return EntityType_UNKNOWN
}

func (x *AddEntityRequest) GetAddress() *common_types.EntityAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type RemoveEntityRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Address       *common_types.EntityAddress `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEntityRequest) Reset() {
	*x = RemoveEntityRequest{}
	mi := &file_control_service_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEntityRequest) ProtoMessage() {}

func (x *RemoveEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEntityRequest.ProtoReflect.Descriptor instead.
func (*RemoveEntityRequest) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveEntityRequest) GetAddress() *common_types.EntityAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type AddUseCaseRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	EntityAddress *common_types.EntityAddress `protobuf:"bytes,1,opt,name=entity_address,json=entityAddress,proto3" json:"entity_address,omitempty"`
	UseCase       *UseCase                    `protobuf:"bytes,2,opt,name=use_case,json=useCase,proto3" json:"use_case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUseCaseRequest) Reset() {
	*x = AddUseCaseRequest{}
	mi := &file_control_service_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUseCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUseCaseRequest) ProtoMessage() {}

func (x *AddUseCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUseCaseRequest.ProtoReflect.Descriptor instead.
func (*AddUseCaseRequest) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{5}
}

func (x *AddUseCaseRequest) GetEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.EntityAddress
	}
	return nil
}

func (x *AddUseCaseRequest) GetUseCase() *UseCase {
	if x != nil {
		return x.UseCase
	}
	return nil
}

type AddUseCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUseCaseResponse) Reset() {
	*x = AddUseCaseResponse{}
	mi := &file_control_service_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUseCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUseCaseResponse) ProtoMessage() {}

func (x *AddUseCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUseCaseResponse.ProtoReflect.Descriptor instead.
func (*AddUseCaseResponse) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{6}
}

func (x *AddUseCaseResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type RegisterRemoteSkiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteSki     string                 `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRemoteSkiRequest) Reset() {
	*x = RegisterRemoteSkiRequest{}
	mi := &file_control_service_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRemoteSkiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRemoteSkiRequest) ProtoMessage() {}

func (x *RegisterRemoteSkiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRemoteSkiRequest.ProtoReflect.Descriptor instead.
func (*RegisterRemoteSkiRequest) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterRemoteSkiRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

type SubscribeUseCaseEventsRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	EntityAddress *common_types.EntityAddress `protobuf:"bytes,1,opt,name=entity_address,json=entityAddress,proto3" json:"entity_address,omitempty"`
	UseCase       *UseCase                    `protobuf:"bytes,2,opt,name=use_case,json=useCase,proto3" json:"use_case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeUseCaseEventsRequest) Reset() {
	*x = SubscribeUseCaseEventsRequest{}
	mi := &file_control_service_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeUseCaseEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeUseCaseEventsRequest) ProtoMessage() {}

func (x *SubscribeUseCaseEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeUseCaseEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeUseCaseEventsRequest) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeUseCaseEventsRequest) GetEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.EntityAddress
	}
	return nil
}

func (x *SubscribeUseCaseEventsRequest) GetUseCase() *UseCase {
	if x != nil {
		return x.UseCase
	}
	return nil
}

type SubscribeUseCaseEventsResponse struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	UseCaseEvent        *UseCaseEvent               `protobuf:"bytes,3,opt,name=use_case_event,json=useCaseEvent,proto3" json:"use_case_event,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeUseCaseEventsResponse) Reset() {
	*x = SubscribeUseCaseEventsResponse{}
	mi := &file_control_service_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeUseCaseEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeUseCaseEventsResponse) ProtoMessage() {}

func (x *SubscribeUseCaseEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeUseCaseEventsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeUseCaseEventsResponse) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeUseCaseEventsResponse) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *SubscribeUseCaseEventsResponse) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

func (x *SubscribeUseCaseEventsResponse) GetUseCaseEvent() *UseCaseEvent {
	if x != nil {
		return x.UseCaseEvent
	}
	return nil
}

type SubscribeDiscoveryEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeDiscoveryEventsRequest) Reset() {
	*x = SubscribeDiscoveryEventsRequest{}
	mi := &file_control_service_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeDiscoveryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeDiscoveryEventsRequest) ProtoMessage() {}

func (x *SubscribeDiscoveryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeDiscoveryEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeDiscoveryEventsRequest) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{10}
}

type DiscoveryEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           DiscoveryEvent_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=control_service.DiscoveryEvent_Type" json:"type,omitempty"` // kind of event: a peer appeared or disappeared from mDNS
	RemoteSki      string                 `protobuf:"bytes,2,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`                // normalized hex, lowercase
	ShipIdentifier string                 `protobuf:"bytes,3,opt,name=ship_identifier,json=shipIdentifier,proto3" json:"ship_identifier,omitempty"` // mDNS `id=` TXT — maps to RemoteService.Identifier
	Brand          string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`                                         // mDNS `brand=` TXT
	Model          string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`                                         // mDNS `model=` TXT
	DeviceType     string                 `protobuf:"bytes,6,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`             // mDNS `type=` TXT — maps to RemoteService.Type
	Serial         string                 `protobuf:"bytes,7,opt,name=serial,proto3" json:"serial,omitempty"`                                       // mDNS `serial=` TXT (optional)
	IsTrusted      bool                   `protobuf:"varint,8,opt,name=is_trusted,json=isTrusted,proto3" json:"is_trusted,omitempty"`               // snapshot of sidecar trust state at event time; see RegisterRemoteSki
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiscoveryEvent) Reset() {
	*x = DiscoveryEvent{}
	mi := &file_control_service_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryEvent) ProtoMessage() {}

func (x *DiscoveryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryEvent.ProtoReflect.Descriptor instead.
func (*DiscoveryEvent) Descriptor() ([]byte, []int) {
	return file_control_service_messages_proto_rawDescGZIP(), []int{11}
}

func (x *DiscoveryEvent) GetType() DiscoveryEvent_Type {
	if x != nil {
		return x.Type
	}
	return DiscoveryEvent_UNKNOWN
}

func (x *DiscoveryEvent) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *DiscoveryEvent) GetShipIdentifier() string {
	if x != nil {
		return x.ShipIdentifier
	}
	return ""
}

func (x *DiscoveryEvent) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *DiscoveryEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DiscoveryEvent) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *DiscoveryEvent) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DiscoveryEvent) GetIsTrusted() bool {
	if x != nil {
		return x.IsTrusted
	}
	return false
}

var File_control_service_messages_proto protoreflect.FileDescriptor

const file_control_service_messages_proto_rawDesc = "" +
	"\n" +
	"\x1econtrol_service/messages.proto\x12\x0fcontrol_service\x1a\x1bcontrol_service/types.proto\x1a\x18common_types/types.proto\"\x0e\n" +
	"\fEmptyRequest\"\x0f\n" +
	"\rEmptyResponse\"\xc9\x03\n" +
	"\x10SetConfigRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x1f\n" +
	"\vvendor_code\x18\x02 \x01(\tR\n" +
	"vendorCode\x12!\n" +
	"\fdevice_brand\x18\x03 \x01(\tR\vdeviceBrand\x12!\n" +
	"\fdevice_model\x18\x04 \x01(\tR\vdeviceModel\x12#\n" +
	"\rserial_number\x18\x05 \x01(\tR\fserialNumber\x12Q\n" +
	"\x11device_categories\x18\x06 \x03(\x0e2$.control_service.DeviceCategory.EnumR\x10deviceCategories\x12A\n" +
	"\vdevice_type\x18\a \x01(\x0e2 .control_service.DeviceType.EnumR\n" +
	"deviceType\x12C\n" +
	"\fentity_types\x18\b \x03(\x0e2 .control_service.EntityType.EnumR\ventityTypes\x12:\n" +
	"\x19heartbeat_timeout_seconds\x18\t \x01(\rR\x17heartbeatTimeoutSeconds\"\x7f\n" +
	"\x10AddEntityRequest\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .control_service.EntityType.EnumR\x04type\x125\n" +
	"\aaddress\x18\x02 \x01(\v2\x1b.common_types.EntityAddressR\aaddress\"L\n" +
	"\x13RemoveEntityRequest\x125\n" +
	"\aaddress\x18\x01 \x01(\v2\x1b.common_types.EntityAddressR\aaddress\"\x8c\x01\n" +
	"\x11AddUseCaseRequest\x12B\n" +
	"\x0eentity_address\x18\x01 \x01(\v2\x1b.common_types.EntityAddressR\rentityAddress\x123\n" +
	"\buse_case\x18\x02 \x01(\v2\x18.control_service.UseCaseR\auseCase\"0\n" +
	"\x12AddUseCaseResponse\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"9\n" +
	"\x18RegisterRemoteSkiRequest\x12\x1d\n" +
	"\n" +
	"remote_ski\x18\x01 \x01(\tR\tremoteSki\"\x98\x01\n" +
	"\x1dSubscribeUseCaseEventsRequest\x12B\n" +
	"\x0eentity_address\x18\x01 \x01(\v2\x1b.common_types.EntityAddressR\rentityAddress\x123\n" +
	"\buse_case\x18\x02 \x01(\v2\x18.control_service.UseCaseR\auseCase\"\xd5\x01\n" +
	"\x1eSubscribeUseCaseEventsResponse\x12\x1d\n" +
	"\n" +
	"remote_ski\x18\x01 \x01(\tR\tremoteSki\x12O\n" +
	"\x15remote_entity_address\x18\x02 \x01(\v2\x1b.common_types.EntityAddressR\x13remoteEntityAddress\x12C\n" +
	"\x0euse_case_event\x18\x03 \x01(\v2\x1d.control_service.UseCaseEventR\fuseCaseEvent\"!\n" +
	"\x1fSubscribeDiscoveryEventsRequest\"\xc8\x02\n" +
	"\x0eDiscoveryEvent\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.control_service.DiscoveryEvent.TypeR\x04type\x12\x1d\n" +
	"\n" +
	"remote_ski\x18\x02 \x01(\tR\tremoteSki\x12'\n" +
	"\x0fship_identifier\x18\x03 \x01(\tR\x0eshipIdentifier\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1f\n" +
	"\vdevice_type\x18\x06 \x01(\tR\n" +
	"deviceType\x12\x16\n" +
	"\x06serial\x18\a \x01(\tR\x06serial\x12\x1d\n" +
	"\n" +
	"is_trusted\x18\b \x01(\bR\tisTrusted\"0\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"DISCOVERED\x10\x01\x12\v\n" +
	"\aREMOVED\x10\x02B=Z;github.com/enbility/eebus-grpc/rpc_services/control_serviceb\x06proto3"

var (
	file_control_service_messages_proto_rawDescOnce sync.Once
	file_control_service_messages_proto_rawDescData []byte
)

func file_control_service_messages_proto_rawDescGZIP() []byte {
	file_control_service_messages_proto_rawDescOnce.Do(func() {
		file_control_service_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_service_messages_proto_rawDesc), len(file_control_service_messages_proto_rawDesc)))
	})
	return file_control_service_messages_proto_rawDescData
}

var file_control_service_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_service_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_control_service_messages_proto_goTypes = []any{
	(DiscoveryEvent_Type)(0),                // 0: control_service.DiscoveryEvent.Type
	(*EmptyRequest)(nil),                    // 1: control_service.EmptyRequest
	(*EmptyResponse)(nil),                   // 2: control_service.EmptyResponse
	(*SetConfigRequest)(nil),                // 3: control_service.SetConfigRequest
	(*AddEntityRequest)(nil),                // 4: control_service.AddEntityRequest
	(*RemoveEntityRequest)(nil),             // 5: control_service.RemoveEntityRequest
	(*AddUseCaseRequest)(nil),               // 6: control_service.AddUseCaseRequest
	(*AddUseCaseResponse)(nil),              // 7: control_service.AddUseCaseResponse
	(*RegisterRemoteSkiRequest)(nil),        // 8: control_service.RegisterRemoteSkiRequest
	(*SubscribeUseCaseEventsRequest)(nil),   // 9: control_service.SubscribeUseCaseEventsRequest
	(*SubscribeUseCaseEventsResponse)(nil),  // 10: control_service.SubscribeUseCaseEventsResponse
	(*SubscribeDiscoveryEventsRequest)(nil), // 11: control_service.SubscribeDiscoveryEventsRequest
	(*DiscoveryEvent)(nil),                  // 12: control_service.DiscoveryEvent
	(DeviceCategory_Enum)(0),                // 13: control_service.DeviceCategory.Enum
	(DeviceType_Enum)(0),                    // 14: control_service.DeviceType.Enum
	(EntityType_Enum)(0),                    // 15: control_service.EntityType.Enum
	(*common_types.EntityAddress)(nil),      // 16: common_types.EntityAddress
	(*UseCase)(nil),                         // 17: control_service.UseCase
	(*UseCaseEvent)(nil),                    // 18: control_service.UseCaseEvent
}
var file_control_service_messages_proto_depIdxs = []int32{
	13, // 0: control_service.SetConfigRequest.device_categories:type_name -> control_service.DeviceCategory.Enum
	14, // 1: control_service.SetConfigRequest.device_type:type_name -> control_service.DeviceType.Enum
	15, // 2: control_service.SetConfigRequest.entity_types:type_name -> control_service.EntityType.Enum
	15, // 3: control_service.AddEntityRequest.type:type_name -> control_service.EntityType.Enum
	16, // 4: control_service.AddEntityRequest.address:type_name -> common_types.EntityAddress
	16, // 5: control_service.RemoveEntityRequest.address:type_name -> common_types.EntityAddress
	16, // 6: control_service.AddUseCaseRequest.entity_address:type_name -> common_types.EntityAddress
	17, // 7: control_service.AddUseCaseRequest.use_case:type_name -> control_service.UseCase
	16, // 8: control_service.SubscribeUseCaseEventsRequest.entity_address:type_name -> common_types.EntityAddress
	17, // 9: control_service.SubscribeUseCaseEventsRequest.use_case:type_name -> control_service.UseCase
	16, // 10: control_service.SubscribeUseCaseEventsResponse.remote_entity_address:type_name -> common_types.EntityAddress
	18, // 11: control_service.SubscribeUseCaseEventsResponse.use_case_event:type_name -> control_service.UseCaseEvent
	0,  // 12: control_service.DiscoveryEvent.type:type_name -> control_service.DiscoveryEvent.Type
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_control_service_messages_proto_init() }
func file_control_service_messages_proto_init() {
	if File_control_service_messages_proto != nil {
		return
	}
	file_control_service_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_service_messages_proto_rawDesc), len(file_control_service_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_service_messages_proto_goTypes,
		DependencyIndexes: file_control_service_messages_proto_depIdxs,
		EnumInfos:         file_control_service_messages_proto_enumTypes,
		MessageInfos:      file_control_service_messages_proto_msgTypes,
	}.Build()
	File_control_service_messages_proto = out.File
	file_control_service_messages_proto_goTypes = nil
	file_control_service_messages_proto_depIdxs = nil
}
