// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: control_service/types.proto

package control_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SharedType int32

const (
	SharedType_INVERTER SharedType = 0
)

// Enum value maps for SharedType.
var (
	SharedType_name = map[int32]string{
		0: "INVERTER",
	}
	SharedType_value = map[string]int32{
		"INVERTER": 0,
	}
)

func (x SharedType) Enum() *SharedType {
	p := new(SharedType)
	*p = x
	return p
}

func (x SharedType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SharedType) Descriptor() protoreflect.EnumDescriptor {
	return file_control_service_types_proto_enumTypes[0].Descriptor()
}

func (SharedType) Type() protoreflect.EnumType {
	return &file_control_service_types_proto_enumTypes[0]
}

func (x SharedType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SharedType.Descriptor instead.
func (SharedType) EnumDescriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{0}
}

type DeviceCategory_Enum int32

const (
	DeviceCategory_UNKNOWN                  DeviceCategory_Enum = 0
	DeviceCategory_GRID_CONNECTION_HUB      DeviceCategory_Enum = 1
	DeviceCategory_ENERGY_MANAGEMENT_SYSTEM DeviceCategory_Enum = 2
	DeviceCategory_E_MOBILITY               DeviceCategory_Enum = 3
	DeviceCategory_HVAC                     DeviceCategory_Enum = 4
	DeviceCategory_INVERTER                 DeviceCategory_Enum = 5
	DeviceCategory_DOMESTIC_APPLIANCE       DeviceCategory_Enum = 6
	DeviceCategory_METERING                 DeviceCategory_Enum = 7
)

// Enum value maps for DeviceCategory_Enum.
var (
	DeviceCategory_Enum_name = map[int32]string{
		0: "UNKNOWN",
		1: "GRID_CONNECTION_HUB",
		2: "ENERGY_MANAGEMENT_SYSTEM",
		3: "E_MOBILITY",
		4: "HVAC",
		5: "INVERTER",
		6: "DOMESTIC_APPLIANCE",
		7: "METERING",
	}
	DeviceCategory_Enum_value = map[string]int32{
		"UNKNOWN":                  0,
		"GRID_CONNECTION_HUB":      1,
		"ENERGY_MANAGEMENT_SYSTEM": 2,
		"E_MOBILITY":               3,
		"HVAC":                     4,
		"INVERTER":                 5,
		"DOMESTIC_APPLIANCE":       6,
		"METERING":                 7,
	}
)

func (x DeviceCategory_Enum) Enum() *DeviceCategory_Enum {
	p := new(DeviceCategory_Enum)
	*p = x
	return p
}

func (x DeviceCategory_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCategory_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_control_service_types_proto_enumTypes[1].Descriptor()
}

func (DeviceCategory_Enum) Type() protoreflect.EnumType {
	return &file_control_service_types_proto_enumTypes[1]
}

func (x DeviceCategory_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceCategory_Enum.Descriptor instead.
func (DeviceCategory_Enum) EnumDescriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{0, 0}
}

type EntityType_Enum int32

const (
	EntityType_UNKNOWN                       EntityType_Enum = 0
	EntityType_Battery                       EntityType_Enum = 1
	EntityType_Compressor                    EntityType_Enum = 2
	EntityType_DeviceInformation             EntityType_Enum = 3
	EntityType_DHWCircuit                    EntityType_Enum = 4
	EntityType_DHWStorage                    EntityType_Enum = 5
	EntityType_Dishwasher                    EntityType_Enum = 6
	EntityType_Dryer                         EntityType_Enum = 7
	EntityType_ElectricalImmersionHeater     EntityType_Enum = 8
	EntityType_Fan                           EntityType_Enum = 9
	EntityType_GasHeatingAppliance           EntityType_Enum = 10
	EntityType_Generic                       EntityType_Enum = 11
	EntityType_HeatingBufferStorage          EntityType_Enum = 12
	EntityType_HeatingCircuit                EntityType_Enum = 13
	EntityType_HeatingObject                 EntityType_Enum = 14
	EntityType_HeatingZone                   EntityType_Enum = 15
	EntityType_HeatPumpAppliance             EntityType_Enum = 16
	EntityType_HeatSinkCircuit               EntityType_Enum = 17
	EntityType_HeatSourceCircuit             EntityType_Enum = 18
	EntityType_HeatSourceUnit                EntityType_Enum = 19
	EntityType_HvacController                EntityType_Enum = 20
	EntityType_HvacRoom                      EntityType_Enum = 21
	EntityType_InstantDHWHeater              EntityType_Enum = 22
	EntityType_Inverter                      EntityType_Enum = 23
	EntityType_OilHeatingAppliance           EntityType_Enum = 24
	EntityType_Pump                          EntityType_Enum = 25
	EntityType_RefrigerantCircuit            EntityType_Enum = 26
	EntityType_SmartEnergyAppliance          EntityType_Enum = 27
	EntityType_SolarDHWStorage               EntityType_Enum = 28
	EntityType_SolarThermalCircuit           EntityType_Enum = 29
	EntityType_SubMeterElectricity           EntityType_Enum = 30
	EntityType_TemperatureSensor             EntityType_Enum = 31
	EntityType_Washer                        EntityType_Enum = 32
	EntityType_BatterySystem                 EntityType_Enum = 33
	EntityType_ElectricityGenerationSystem   EntityType_Enum = 34
	EntityType_ElectricityStorageSystem      EntityType_Enum = 35
	EntityType_GridConnectionPointOfPremises EntityType_Enum = 36
	EntityType_Household                     EntityType_Enum = 37
	EntityType_PVSystem                      EntityType_Enum = 38
	EntityType_EV                            EntityType_Enum = 39
	EntityType_EVSE                          EntityType_Enum = 40
	EntityType_ChargingOutlet                EntityType_Enum = 41
	EntityType_CEM                           EntityType_Enum = 42
	EntityType_PV                            EntityType_Enum = 43
	EntityType_PVESHybrid                    EntityType_Enum = 44
	EntityType_ElectricalStorage             EntityType_Enum = 45
	EntityType_PVString                      EntityType_Enum = 46
	EntityType_GridGuard                     EntityType_Enum = 47
	EntityType_ControllableSystem            EntityType_Enum = 48
)

// Enum value maps for EntityType_Enum.
var (
	EntityType_Enum_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "Battery",
		2:  "Compressor",
		3:  "DeviceInformation",
		4:  "DHWCircuit",
		5:  "DHWStorage",
		6:  "Dishwasher",
		7:  "Dryer",
		8:  "ElectricalImmersionHeater",
		9:  "Fan",
		10: "GasHeatingAppliance",
		11: "Generic",
		12: "HeatingBufferStorage",
		13: "HeatingCircuit",
		14: "HeatingObject",
		15: "HeatingZone",
		16: "HeatPumpAppliance",
		17: "HeatSinkCircuit",
		18: "HeatSourceCircuit",
		19: "HeatSourceUnit",
		20: "HvacController",
		21: "HvacRoom",
		22: "InstantDHWHeater",
		23: "Inverter",
		24: "OilHeatingAppliance",
		25: "Pump",
		26: "RefrigerantCircuit",
		27: "SmartEnergyAppliance",
		28: "SolarDHWStorage",
		29: "SolarThermalCircuit",
		30: "SubMeterElectricity",
		31: "TemperatureSensor",
		32: "Washer",
		33: "BatterySystem",
		34: "ElectricityGenerationSystem",
		35: "ElectricityStorageSystem",
		36: "GridConnectionPointOfPremises",
		37: "Household",
		38: "PVSystem",
		39: "EV",
		40: "EVSE",
		41: "ChargingOutlet",
		42: "CEM",
		43: "PV",
		44: "PVESHybrid",
		45: "ElectricalStorage",
		46: "PVString",
		47: "GridGuard",
		48: "ControllableSystem",
	}
	EntityType_Enum_value = map[string]int32{
		"UNKNOWN":                       0,
		"Battery":                       1,
		"Compressor":                    2,
		"DeviceInformation":             3,
		"DHWCircuit":                    4,
		"DHWStorage":                    5,
		"Dishwasher":                    6,
		"Dryer":                         7,
		"ElectricalImmersionHeater":     8,
		"Fan":                           9,
		"GasHeatingAppliance":           10,
		"Generic":                       11,
		"HeatingBufferStorage":          12,
		"HeatingCircuit":                13,
		"HeatingObject":                 14,
		"HeatingZone":                   15,
		"HeatPumpAppliance":             16,
		"HeatSinkCircuit":               17,
		"HeatSourceCircuit":             18,
		"HeatSourceUnit":                19,
		"HvacController":                20,
		"HvacRoom":                      21,
		"InstantDHWHeater":              22,
		"Inverter":                      23,
		"OilHeatingAppliance":           24,
		"Pump":                          25,
		"RefrigerantCircuit":            26,
		"SmartEnergyAppliance":          27,
		"SolarDHWStorage":               28,
		"SolarThermalCircuit":           29,
		"SubMeterElectricity":           30,
		"TemperatureSensor":             31,
		"Washer":                        32,
		"BatterySystem":                 33,
		"ElectricityGenerationSystem":   34,
		"ElectricityStorageSystem":      35,
		"GridConnectionPointOfPremises": 36,
		"Household":                     37,
		"PVSystem":                      38,
		"EV":                            39,
		"EVSE":                          40,
		"ChargingOutlet":                41,
		"CEM":                           42,
		"PV":                            43,
		"PVESHybrid":                    44,
		"ElectricalStorage":             45,
		"PVString":                      46,
		"GridGuard":                     47,
		"ControllableSystem":            48,
	}
)

func (x EntityType_Enum) Enum() *EntityType_Enum {
	p := new(EntityType_Enum)
	*p = x
	return p
}

func (x EntityType_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_control_service_types_proto_enumTypes[2].Descriptor()
}

func (EntityType_Enum) Type() protoreflect.EnumType {
	return &file_control_service_types_proto_enumTypes[2]
}

func (x EntityType_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType_Enum.Descriptor instead.
func (EntityType_Enum) EnumDescriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{1, 0}
}

type DeviceType_Enum int32

const (
	DeviceType_UNKNOWN                   DeviceType_Enum = 0
	DeviceType_DISHWASHER                DeviceType_Enum = 1
	DeviceType_DRYER                     DeviceType_Enum = 2
	DeviceType_ENVIRONMENT_SENSOR        DeviceType_Enum = 3
	DeviceType_GENERIC                   DeviceType_Enum = 4
	DeviceType_HEAT_GENERATION_SYSTEM    DeviceType_Enum = 5
	DeviceType_HEAT_SINK_SYSTEM          DeviceType_Enum = 6
	DeviceType_HEAT_STORAGE_SYSTEM       DeviceType_Enum = 7
	DeviceType_HVAC_CONTROLLER           DeviceType_Enum = 8
	DeviceType_SUBMETER                  DeviceType_Enum = 9
	DeviceType_WASHER                    DeviceType_Enum = 10
	DeviceType_ELECTRICITY_SUPPLY_SYSTEM DeviceType_Enum = 11
	DeviceType_ENERGY_MANAGEMENT_SYSTEM  DeviceType_Enum = 12
	DeviceType_INVERTER                  DeviceType_Enum = 13
	DeviceType_CHARGING_STATION          DeviceType_Enum = 14
)

// Enum value maps for DeviceType_Enum.
var (
	DeviceType_Enum_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "DISHWASHER",
		2:  "DRYER",
		3:  "ENVIRONMENT_SENSOR",
		4:  "GENERIC",
		5:  "HEAT_GENERATION_SYSTEM",
		6:  "HEAT_SINK_SYSTEM",
		7:  "HEAT_STORAGE_SYSTEM",
		8:  "HVAC_CONTROLLER",
		9:  "SUBMETER",
		10: "WASHER",
		11: "ELECTRICITY_SUPPLY_SYSTEM",
		12: "ENERGY_MANAGEMENT_SYSTEM",
		13: "INVERTER",
		14: "CHARGING_STATION",
	}
	DeviceType_Enum_value = map[string]int32{
		"UNKNOWN":                   0,
		"DISHWASHER":                1,
		"DRYER":                     2,
		"ENVIRONMENT_SENSOR":        3,
		"GENERIC":                   4,
		"HEAT_GENERATION_SYSTEM":    5,
		"HEAT_SINK_SYSTEM":          6,
		"HEAT_STORAGE_SYSTEM":       7,
		"HVAC_CONTROLLER":           8,
		"SUBMETER":                  9,
		"WASHER":                    10,
		"ELECTRICITY_SUPPLY_SYSTEM": 11,
		"ENERGY_MANAGEMENT_SYSTEM":  12,
		"INVERTER":                  13,
		"CHARGING_STATION":          14,
	}
)

func (x DeviceType_Enum) Enum() *DeviceType_Enum {
	p := new(DeviceType_Enum)
	*p = x
	return p
}

func (x DeviceType_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_control_service_types_proto_enumTypes[3].Descriptor()
}

func (DeviceType_Enum) Type() protoreflect.EnumType {
	return &file_control_service_types_proto_enumTypes[3]
}

func (x DeviceType_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType_Enum.Descriptor instead.
func (DeviceType_Enum) EnumDescriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{2, 0}
}

type UseCase_ActorType_Enum int32

const (
	UseCase_ActorType_UNKNOWN                  UseCase_ActorType_Enum = 0
	UseCase_ActorType_Battery                  UseCase_ActorType_Enum = 1
	UseCase_ActorType_BatterySystem            UseCase_ActorType_Enum = 2
	UseCase_ActorType_CEM                      UseCase_ActorType_Enum = 3
	UseCase_ActorType_ConfigurationAppliance   UseCase_ActorType_Enum = 4
	UseCase_ActorType_Compressor               UseCase_ActorType_Enum = 5
	UseCase_ActorType_ControllableSystem       UseCase_ActorType_Enum = 6
	UseCase_ActorType_DHWCircuit               UseCase_ActorType_Enum = 7
	UseCase_ActorType_EnergyBroker             UseCase_ActorType_Enum = 8
	UseCase_ActorType_EnergyConsumer           UseCase_ActorType_Enum = 9
	UseCase_ActorType_EnergyGuard              UseCase_ActorType_Enum = 10
	UseCase_ActorType_EVSE                     UseCase_ActorType_Enum = 11
	UseCase_ActorType_EV                       UseCase_ActorType_Enum = 12
	UseCase_ActorType_GridConnectionPoint      UseCase_ActorType_Enum = 13
	UseCase_ActorType_HeatPump                 UseCase_ActorType_Enum = 14
	UseCase_ActorType_HeatingCircuit           UseCase_ActorType_Enum = 15
	UseCase_ActorType_HeatingZone              UseCase_ActorType_Enum = 16
	UseCase_ActorType_HVACRoom                 UseCase_ActorType_Enum = 17
	UseCase_ActorType_Inverter                 UseCase_ActorType_Enum = 18
	UseCase_ActorType_MonitoredUnit            UseCase_ActorType_Enum = 19
	UseCase_ActorType_MonitoringAppliance      UseCase_ActorType_Enum = 20
	UseCase_ActorType_OutdoorTemperatureSensor UseCase_ActorType_Enum = 21
	UseCase_ActorType_PVString                 UseCase_ActorType_Enum = 22
	UseCase_ActorType_PVSystem                 UseCase_ActorType_Enum = 23
	UseCase_ActorType_SmartAppliance           UseCase_ActorType_Enum = 24
	UseCase_ActorType_VisualizationAppliance   UseCase_ActorType_Enum = 25
)

// Enum value maps for UseCase_ActorType_Enum.
var (
	UseCase_ActorType_Enum_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "Battery",
		2:  "BatterySystem",
		3:  "CEM",
		4:  "ConfigurationAppliance",
		5:  "Compressor",
		6:  "ControllableSystem",
		7:  "DHWCircuit",
		8:  "EnergyBroker",
		9:  "EnergyConsumer",
		10: "EnergyGuard",
		11: "EVSE",
		12: "EV",
		13: "GridConnectionPoint",
		14: "HeatPump",
		15: "HeatingCircuit",
		16: "HeatingZone",
		17: "HVACRoom",
		18: "Inverter",
		19: "MonitoredUnit",
		20: "MonitoringAppliance",
		21: "OutdoorTemperatureSensor",
		22: "PVString",
		23: "PVSystem",
		24: "SmartAppliance",
		25: "VisualizationAppliance",
	}
	UseCase_ActorType_Enum_value = map[string]int32{
		"UNKNOWN":                  0,
		"Battery":                  1,
		"BatterySystem":            2,
		"CEM":                      3,
		"ConfigurationAppliance":   4,
		"Compressor":               5,
		"ControllableSystem":       6,
		"DHWCircuit":               7,
		"EnergyBroker":             8,
		"EnergyConsumer":           9,
		"EnergyGuard":              10,
		"EVSE":                     11,
		"EV":                       12,
		"GridConnectionPoint":      13,
		"HeatPump":                 14,
		"HeatingCircuit":           15,
		"HeatingZone":              16,
		"HVACRoom":                 17,
		"Inverter":                 18,
		"MonitoredUnit":            19,
		"MonitoringAppliance":      20,
		"OutdoorTemperatureSensor": 21,
		"PVString":                 22,
		"PVSystem":                 23,
		"SmartAppliance":           24,
		"VisualizationAppliance":   25,
	}
)

func (x UseCase_ActorType_Enum) Enum() *UseCase_ActorType_Enum {
	p := new(UseCase_ActorType_Enum)
	*p = x
	return p
}

func (x UseCase_ActorType_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UseCase_ActorType_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_control_service_types_proto_enumTypes[4].Descriptor()
}

func (UseCase_ActorType_Enum) Type() protoreflect.EnumType {
	return &file_control_service_types_proto_enumTypes[4]
}

func (x UseCase_ActorType_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UseCase_ActorType_Enum.Descriptor instead.
func (UseCase_ActorType_Enum) EnumDescriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{3, 0, 0}
}

type UseCase_NameType_Enum int32

const (
	UseCase_NameType_UNKNOWN                                                      UseCase_NameType_Enum = 0
	UseCase_NameType_configurationOfDhwSystemFunction                             UseCase_NameType_Enum = 1
	UseCase_NameType_configurationOfDhwTemperature                                UseCase_NameType_Enum = 2
	UseCase_NameType_configurationOfRoomCoolingSystemFunction                     UseCase_NameType_Enum = 3
	UseCase_NameType_configurationOfRoomCoolingTemperature                        UseCase_NameType_Enum = 4
	UseCase_NameType_configurationOfRoomHeatingSystemFunction                     UseCase_NameType_Enum = 5
	UseCase_NameType_configurationOfRoomHeatingTemperature                        UseCase_NameType_Enum = 6
	UseCase_NameType_controlOfBattery                                             UseCase_NameType_Enum = 7
	UseCase_NameType_coordinatedEvCharging                                        UseCase_NameType_Enum = 8
	UseCase_NameType_evChargingSummary                                            UseCase_NameType_Enum = 9
	UseCase_NameType_evCommissioningAndConfiguration                              UseCase_NameType_Enum = 10
	UseCase_NameType_evseCommissioningAndConfiguration                            UseCase_NameType_Enum = 11
	UseCase_NameType_evStateOfCharge                                              UseCase_NameType_Enum = 12
	UseCase_NameType_flexibleLoad                                                 UseCase_NameType_Enum = 13
	UseCase_NameType_flexibleStartForWhiteGoods                                   UseCase_NameType_Enum = 14
	UseCase_NameType_limitationOfPowerConsumption                                 UseCase_NameType_Enum = 15
	UseCase_NameType_limitationOfPowerProduction                                  UseCase_NameType_Enum = 16
	UseCase_NameType_incentiveTableBasedPowerConsumptionManagement                UseCase_NameType_Enum = 17
	UseCase_NameType_measurementOfElectricityDuringEvCharging                     UseCase_NameType_Enum = 18
	UseCase_NameType_monitoringAndControlOfSmartGridReadyConditions               UseCase_NameType_Enum = 19
	UseCase_NameType_monitoringOfBattery                                          UseCase_NameType_Enum = 20
	UseCase_NameType_monitoringOfDhwSystemFunction                                UseCase_NameType_Enum = 21
	UseCase_NameType_monitoringOfDhwTemperature                                   UseCase_NameType_Enum = 22
	UseCase_NameType_monitoringOfGridConnectionPoint                              UseCase_NameType_Enum = 23
	UseCase_NameType_monitoringOfInverter                                         UseCase_NameType_Enum = 24
	UseCase_NameType_monitoringOfOutdoorTemperature                               UseCase_NameType_Enum = 25
	UseCase_NameType_monitoringOfPowerConsumption                                 UseCase_NameType_Enum = 26
	UseCase_NameType_monitoringOfPvString                                         UseCase_NameType_Enum = 27
	UseCase_NameType_monitoringOfRoomCoolingSystemFunction                        UseCase_NameType_Enum = 28
	UseCase_NameType_monitoringOfRoomHeatingSystemFunction                        UseCase_NameType_Enum = 29
	UseCase_NameType_monitoringOfRoomTemperature                                  UseCase_NameType_Enum = 30
	UseCase_NameType_optimizationOfSelfConsumptionByHeatPumpCompressorFlexibility UseCase_NameType_Enum = 31
	UseCase_NameType_optimizationOfSelfConsumptionDuringEvCharging                UseCase_NameType_Enum = 32
	UseCase_NameType_overloadProtectionByEvChargingCurrentCurtailment             UseCase_NameType_Enum = 33
	UseCase_NameType_visualizationOfAggregatedBatteryData                         UseCase_NameType_Enum = 34
	UseCase_NameType_visualizationOfAggregatedPhotovoltaicData                    UseCase_NameType_Enum = 35
	UseCase_NameType_visualizationOfHeatingAreaName                               UseCase_NameType_Enum = 36
)

// Enum value maps for UseCase_NameType_Enum.
var (
	UseCase_NameType_Enum_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "configurationOfDhwSystemFunction",
		2:  "configurationOfDhwTemperature",
		3:  "configurationOfRoomCoolingSystemFunction",
		4:  "configurationOfRoomCoolingTemperature",
		5:  "configurationOfRoomHeatingSystemFunction",
		6:  "configurationOfRoomHeatingTemperature",
		7:  "controlOfBattery",
		8:  "coordinatedEvCharging",
		9:  "evChargingSummary",
		10: "evCommissioningAndConfiguration",
		11: "evseCommissioningAndConfiguration",
		12: "evStateOfCharge",
		13: "flexibleLoad",
		14: "flexibleStartForWhiteGoods",
		15: "limitationOfPowerConsumption",
		16: "limitationOfPowerProduction",
		17: "incentiveTableBasedPowerConsumptionManagement",
		18: "measurementOfElectricityDuringEvCharging",
		19: "monitoringAndControlOfSmartGridReadyConditions",
		20: "monitoringOfBattery",
		21: "monitoringOfDhwSystemFunction",
		22: "monitoringOfDhwTemperature",
		23: "monitoringOfGridConnectionPoint",
		24: "monitoringOfInverter",
		25: "monitoringOfOutdoorTemperature",
		26: "monitoringOfPowerConsumption",
		27: "monitoringOfPvString",
		28: "monitoringOfRoomCoolingSystemFunction",
		29: "monitoringOfRoomHeatingSystemFunction",
		30: "monitoringOfRoomTemperature",
		31: "optimizationOfSelfConsumptionByHeatPumpCompressorFlexibility",
		32: "optimizationOfSelfConsumptionDuringEvCharging",
		33: "overloadProtectionByEvChargingCurrentCurtailment",
		34: "visualizationOfAggregatedBatteryData",
		35: "visualizationOfAggregatedPhotovoltaicData",
		36: "visualizationOfHeatingAreaName",
	}
	UseCase_NameType_Enum_value = map[string]int32{
		"UNKNOWN":                                                      0,
		"configurationOfDhwSystemFunction":                             1,
		"configurationOfDhwTemperature":                                2,
		"configurationOfRoomCoolingSystemFunction":                     3,
		"configurationOfRoomCoolingTemperature":                        4,
		"configurationOfRoomHeatingSystemFunction":                     5,
		"configurationOfRoomHeatingTemperature":                        6,
		"controlOfBattery":                                             7,
		"coordinatedEvCharging":                                        8,
		"evChargingSummary":                                            9,
		"evCommissioningAndConfiguration":                              10,
		"evseCommissioningAndConfiguration":                            11,
		"evStateOfCharge":                                              12,
		"flexibleLoad":                                                 13,
		"flexibleStartForWhiteGoods":                                   14,
		"limitationOfPowerConsumption":                                 15,
		"limitationOfPowerProduction":                                  16,
		"incentiveTableBasedPowerConsumptionManagement":                17,
		"measurementOfElectricityDuringEvCharging":                     18,
		"monitoringAndControlOfSmartGridReadyConditions":               19,
		"monitoringOfBattery":                                          20,
		"monitoringOfDhwSystemFunction":                                21,
		"monitoringOfDhwTemperature":                                   22,
		"monitoringOfGridConnectionPoint":                              23,
		"monitoringOfInverter":                                         24,
		"monitoringOfOutdoorTemperature":                               25,
		"monitoringOfPowerConsumption":                                 26,
		"monitoringOfPvString":                                         27,
		"monitoringOfRoomCoolingSystemFunction":                        28,
		"monitoringOfRoomHeatingSystemFunction":                        29,
		"monitoringOfRoomTemperature":                                  30,
		"optimizationOfSelfConsumptionByHeatPumpCompressorFlexibility": 31,
		"optimizationOfSelfConsumptionDuringEvCharging":                32,
		"overloadProtectionByEvChargingCurrentCurtailment":             33,
		"visualizationOfAggregatedBatteryData":                         34,
		"visualizationOfAggregatedPhotovoltaicData":                    35,
		"visualizationOfHeatingAreaName":                               36,
	}
)

func (x UseCase_NameType_Enum) Enum() *UseCase_NameType_Enum {
	p := new(UseCase_NameType_Enum)
	*p = x
	return p
}

func (x UseCase_NameType_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UseCase_NameType_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_control_service_types_proto_enumTypes[5].Descriptor()
}

func (UseCase_NameType_Enum) Type() protoreflect.EnumType {
	return &file_control_service_types_proto_enumTypes[5]
}

func (x UseCase_NameType_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UseCase_NameType_Enum.Descriptor instead.
func (UseCase_NameType_Enum) EnumDescriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{3, 1, 0}
}

type DeviceCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCategory) Reset() {
	*x = DeviceCategory{}
	mi := &file_control_service_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCategory) ProtoMessage() {}

func (x *DeviceCategory) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCategory.ProtoReflect.Descriptor instead.
func (*DeviceCategory) Descriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{0}
}

type EntityType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityType) Reset() {
	*x = EntityType{}
	mi := &file_control_service_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityType) ProtoMessage() {}

func (x *EntityType) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityType.ProtoReflect.Descriptor instead.
func (*EntityType) Descriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{1}
}

type DeviceType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceType) Reset() {
	*x = DeviceType{}
	mi := &file_control_service_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceType) ProtoMessage() {}

func (x *DeviceType) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceType.ProtoReflect.Descriptor instead.
func (*DeviceType) Descriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{2}
}

type UseCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         UseCase_ActorType_Enum `protobuf:"varint,1,opt,name=actor,proto3,enum=control_service.UseCase_ActorType_Enum" json:"actor,omitempty"`
	Name          UseCase_NameType_Enum  `protobuf:"varint,2,opt,name=name,proto3,enum=control_service.UseCase_NameType_Enum" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCase) Reset() {
	*x = UseCase{}
	mi := &file_control_service_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCase) ProtoMessage() {}

func (x *UseCase) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCase.ProtoReflect.Descriptor instead.
func (*UseCase) Descriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{3}
}

func (x *UseCase) GetActor() UseCase_ActorType_Enum {
	if x != nil {
		return x.Actor
	}
	return UseCase_ActorType_UNKNOWN
}

func (x *UseCase) GetName() UseCase_NameType_Enum {
	if x != nil {
		return x.Name
	}
	return UseCase_NameType_UNKNOWN
}

type UseCaseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UseCase       *UseCase               `protobuf:"bytes,1,opt,name=use_case,json=useCase,proto3" json:"use_case,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCaseEvent) Reset() {
	*x = UseCaseEvent{}
	mi := &file_control_service_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCaseEvent) ProtoMessage() {}

func (x *UseCaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCaseEvent.ProtoReflect.Descriptor instead.
func (*UseCaseEvent) Descriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{4}
}

func (x *UseCaseEvent) GetUseCase() *UseCase {
	if x != nil {
		return x.UseCase
	}
	return nil
}

func (x *UseCaseEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type UseCase_ActorType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCase_ActorType) Reset() {
	*x = UseCase_ActorType{}
	mi := &file_control_service_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCase_ActorType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCase_ActorType) ProtoMessage() {}

func (x *UseCase_ActorType) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCase_ActorType.ProtoReflect.Descriptor instead.
func (*UseCase_ActorType) Descriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{3, 0}
}

type UseCase_NameType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCase_NameType) Reset() {
	*x = UseCase_NameType{}
	mi := &file_control_service_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCase_NameType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCase_NameType) ProtoMessage() {}

func (x *UseCase_NameType) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCase_NameType.ProtoReflect.Descriptor instead.
func (*UseCase_NameType) Descriptor() ([]byte, []int) {
	return file_control_service_types_proto_rawDescGZIP(), []int{3, 1}
}

var File_control_service_types_proto protoreflect.FileDescriptor

const file_control_service_types_proto_rawDesc = "" +
	"\n" +
	"\x1bcontrol_service/types.proto\x12\x0fcontrol_service\"\xab\x01\n" +
	"\x0eDeviceCategory\"\x98\x01\n" +
	"\x04Enum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x17\n" +
	"\x13GRID_CONNECTION_HUB\x10\x01\x12\x1c\n" +
	"\x18ENERGY_MANAGEMENT_SYSTEM\x10\x02\x12\x0e\n" +
	"\n" +
	"E_MOBILITY\x10\x03\x12\b\n" +
	"\x04HVAC\x10\x04\x12\f\n" +
	"\bINVERTER\x10\x05\x12\x16\n" +
	"\x12DOMESTIC_APPLIANCE\x10\x06\x12\f\n" +
	"\bMETERING\x10\a\"\xb2\a\n" +
	"\n" +
	"EntityType\"\xa3\a\n" +
	"\x04Enum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aBattery\x10\x01\x12\x0e\n" +
	"\n" +
	"Compressor\x10\x02\x12\x15\n" +
	"\x11DeviceInformation\x10\x03\x12\x0e\n" +
	"\n" +
	"DHWCircuit\x10\x04\x12\x0e\n" +
	"\n" +
	"DHWStorage\x10\x05\x12\x0e\n" +
	"\n" +
	"Dishwasher\x10\x06\x12\t\n" +
	"\x05Dryer\x10\a\x12\x1d\n" +
	"\x19ElectricalImmersionHeater\x10\b\x12\a\n" +
	"\x03Fan\x10\t\x12\x17\n" +
	"\x13GasHeatingAppliance\x10\n" +
	"\x12\v\n" +
	"\aGeneric\x10\v\x12\x18\n" +
	"\x14HeatingBufferStorage\x10\f\x12\x12\n" +
	"\x0eHeatingCircuit\x10\r\x12\x11\n" +
	"\rHeatingObject\x10\x0e\x12\x0f\n" +
	"\vHeatingZone\x10\x0f\x12\x15\n" +
	"\x11HeatPumpAppliance\x10\x10\x12\x13\n" +
	"\x0fHeatSinkCircuit\x10\x11\x12\x15\n" +
	"\x11HeatSourceCircuit\x10\x12\x12\x12\n" +
	"\x0eHeatSourceUnit\x10\x13\x12\x12\n" +
	"\x0eHvacController\x10\x14\x12\f\n" +
	"\bHvacRoom\x10\x15\x12\x14\n" +
	"\x10InstantDHWHeater\x10\x16\x12\f\n" +
	"\bInverter\x10\x17\x12\x17\n" +
	"\x13OilHeatingAppliance\x10\x18\x12\b\n" +
	"\x04Pump\x10\x19\x12\x16\n" +
	"\x12RefrigerantCircuit\x10\x1a\x12\x18\n" +
	"\x14SmartEnergyAppliance\x10\x1b\x12\x13\n" +
	"\x0fSolarDHWStorage\x10\x1c\x12\x17\n" +
	"\x13SolarThermalCircuit\x10\x1d\x12\x17\n" +
	"\x13SubMeterElectricity\x10\x1e\x12\x15\n" +
	"\x11TemperatureSensor\x10\x1f\x12\n" +
	"\n" +
	"\x06Washer\x10 \x12\x11\n" +
	"\rBatterySystem\x10!\x12\x1f\n" +
	"\x1bElectricityGenerationSystem\x10\"\x12\x1c\n" +
	"\x18ElectricityStorageSystem\x10#\x12!\n" +
	"\x1dGridConnectionPointOfPremises\x10$\x12\r\n" +
	"\tHousehold\x10%\x12\f\n" +
	"\bPVSystem\x10&\x12\x06\n" +
	"\x02EV\x10'\x12\b\n" +
	"\x04EVSE\x10(\x12\x12\n" +
	"\x0eChargingOutlet\x10)\x12\a\n" +
	"\x03CEM\x10*\x12\x06\n" +
	"\x02PV\x10+\x12\x0e\n" +
	"\n" +
	"PVESHybrid\x10,\x12\x15\n" +
	"\x11ElectricalStorage\x10-\x12\f\n" +
	"\bPVString\x10.\x12\r\n" +
	"\tGridGuard\x10/\x12\x16\n" +
	"\x12ControllableSystem\x100\"\xbd\x02\n" +
	"\n" +
	"DeviceType\"\xae\x02\n" +
	"\x04Enum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"DISHWASHER\x10\x01\x12\t\n" +
	"\x05DRYER\x10\x02\x12\x16\n" +
	"\x12ENVIRONMENT_SENSOR\x10\x03\x12\v\n" +
	"\aGENERIC\x10\x04\x12\x1a\n" +
	"\x16HEAT_GENERATION_SYSTEM\x10\x05\x12\x14\n" +
	"\x10HEAT_SINK_SYSTEM\x10\x06\x12\x17\n" +
	"\x13HEAT_STORAGE_SYSTEM\x10\a\x12\x13\n" +
	"\x0fHVAC_CONTROLLER\x10\b\x12\f\n" +
	"\bSUBMETER\x10\t\x12\n" +
	"\n" +
	"\x06WASHER\x10\n" +
	"\x12\x1d\n" +
	"\x19ELECTRICITY_SUPPLY_SYSTEM\x10\v\x12\x1c\n" +
	"\x18ENERGY_MANAGEMENT_SYSTEM\x10\f\x12\f\n" +
	"\bINVERTER\x10\r\x12\x14\n" +
	"\x10CHARGING_STATION\x10\x0e\"\xd7\x0f\n" +
	"\aUseCase\x12=\n" +
	"\x05actor\x18\x01 \x01(\x0e2'.control_service.UseCase.ActorType.EnumR\x05actor\x12:\n" +
	"\x04name\x18\x02 \x01(\x0e2&.control_service.UseCase.NameType.EnumR\x04name\x1a\xe5\x03\n" +
	"\tActorType\"\xd7\x03\n" +
	"\x04Enum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aBattery\x10\x01\x12\x11\n" +
	"\rBatterySystem\x10\x02\x12\a\n" +
	"\x03CEM\x10\x03\x12\x1a\n" +
	"\x16ConfigurationAppliance\x10\x04\x12\x0e\n" +
	"\n" +
	"Compressor\x10\x05\x12\x16\n" +
	"\x12ControllableSystem\x10\x06\x12\x0e\n" +
	"\n" +
	"DHWCircuit\x10\a\x12\x10\n" +
	"\fEnergyBroker\x10\b\x12\x12\n" +
	"\x0eEnergyConsumer\x10\t\x12\x0f\n" +
	"\vEnergyGuard\x10\n" +
	"\x12\b\n" +
	"\x04EVSE\x10\v\x12\x06\n" +
	"\x02EV\x10\f\x12\x17\n" +
	"\x13GridConnectionPoint\x10\r\x12\f\n" +
	"\bHeatPump\x10\x0e\x12\x12\n" +
	"\x0eHeatingCircuit\x10\x0f\x12\x0f\n" +
	"\vHeatingZone\x10\x10\x12\f\n" +
	"\bHVACRoom\x10\x11\x12\f\n" +
	"\bInverter\x10\x12\x12\x11\n" +
	"\rMonitoredUnit\x10\x13\x12\x17\n" +
	"\x13MonitoringAppliance\x10\x14\x12\x1c\n" +
	"\x18OutdoorTemperatureSensor\x10\x15\x12\f\n" +
	"\bPVString\x10\x16\x12\f\n" +
	"\bPVSystem\x10\x17\x12\x12\n" +
	"\x0eSmartAppliance\x10\x18\x12\x1a\n" +
	"\x16VisualizationAppliance\x10\x19\x1a\xe8\n" +
	"\n" +
	"\bNameType\"\xdb\n" +
	"\n" +
	"\x04Enum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12$\n" +
	" configurationOfDhwSystemFunction\x10\x01\x12!\n" +
	"\x1dconfigurationOfDhwTemperature\x10\x02\x12,\n" +
	"(configurationOfRoomCoolingSystemFunction\x10\x03\x12)\n" +
	"%configurationOfRoomCoolingTemperature\x10\x04\x12,\n" +
	"(configurationOfRoomHeatingSystemFunction\x10\x05\x12)\n" +
	"%configurationOfRoomHeatingTemperature\x10\x06\x12\x14\n" +
	"\x10controlOfBattery\x10\a\x12\x19\n" +
	"\x15coordinatedEvCharging\x10\b\x12\x15\n" +
	"\x11evChargingSummary\x10\t\x12#\n" +
	"\x1fevCommissioningAndConfiguration\x10\n" +
	"\x12%\n" +
	"!evseCommissioningAndConfiguration\x10\v\x12\x13\n" +
	"\x0fevStateOfCharge\x10\f\x12\x10\n" +
	"\fflexibleLoad\x10\r\x12\x1e\n" +
	"\x1aflexibleStartForWhiteGoods\x10\x0e\x12 \n" +
	"\x1climitationOfPowerConsumption\x10\x0f\x12\x1f\n" +
	"\x1blimitationOfPowerProduction\x10\x10\x121\n" +
	"-incentiveTableBasedPowerConsumptionManagement\x10\x11\x12,\n" +
	"(measurementOfElectricityDuringEvCharging\x10\x12\x122\n" +
	".monitoringAndControlOfSmartGridReadyConditions\x10\x13\x12\x17\n" +
	"\x13monitoringOfBattery\x10\x14\x12!\n" +
	"\x1dmonitoringOfDhwSystemFunction\x10\x15\x12\x1e\n" +
	"\x1amonitoringOfDhwTemperature\x10\x16\x12#\n" +
	"\x1fmonitoringOfGridConnectionPoint\x10\x17\x12\x18\n" +
	"\x14monitoringOfInverter\x10\x18\x12\"\n" +
	"\x1emonitoringOfOutdoorTemperature\x10\x19\x12 \n" +
	"\x1cmonitoringOfPowerConsumption\x10\x1a\x12\x18\n" +
	"\x14monitoringOfPvString\x10\x1b\x12)\n" +
	"%monitoringOfRoomCoolingSystemFunction\x10\x1c\x12)\n" +
	"%monitoringOfRoomHeatingSystemFunction\x10\x1d\x12\x1f\n" +
	"\x1bmonitoringOfRoomTemperature\x10\x1e\x12@\n" +
	"<optimizationOfSelfConsumptionByHeatPumpCompressorFlexibility\x10\x1f\x121\n" +
	"-optimizationOfSelfConsumptionDuringEvCharging\x10 \x124\n" +
	"0overloadProtectionByEvChargingCurrentCurtailment\x10!\x12(\n" +
	"$visualizationOfAggregatedBatteryData\x10\"\x12-\n" +
	")visualizationOfAggregatedPhotovoltaicData\x10#\x12\"\n" +
	"\x1evisualizationOfHeatingAreaName\x10$\"Y\n" +
	"\fUseCaseEvent\x123\n" +
	"\buse_case\x18\x01 \x01(\v2\x18.control_service.UseCaseR\auseCase\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event*\x1a\n" +
	"\n" +
	"SharedType\x12\f\n" +
	"\bINVERTER\x10\x00B=Z;github.com/enbility/eebus-grpc/rpc_services/control_serviceb\x06proto3"

var (
	file_control_service_types_proto_rawDescOnce sync.Once
	file_control_service_types_proto_rawDescData []byte
)

func file_control_service_types_proto_rawDescGZIP() []byte {
	file_control_service_types_proto_rawDescOnce.Do(func() {
		file_control_service_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_service_types_proto_rawDesc), len(file_control_service_types_proto_rawDesc)))
	})
	return file_control_service_types_proto_rawDescData
}

var file_control_service_types_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_control_service_types_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_control_service_types_proto_goTypes = []any{
	(SharedType)(0),             // 0: control_service.SharedType
	(DeviceCategory_Enum)(0),    // 1: control_service.DeviceCategory.Enum
	(EntityType_Enum)(0),        // 2: control_service.EntityType.Enum
	(DeviceType_Enum)(0),        // 3: control_service.DeviceType.Enum
	(UseCase_ActorType_Enum)(0), // 4: control_service.UseCase.ActorType.Enum
	(UseCase_NameType_Enum)(0),  // 5: control_service.UseCase.NameType.Enum
	(*DeviceCategory)(nil),      // 6: control_service.DeviceCategory
	(*EntityType)(nil),          // 7: control_service.EntityType
	(*DeviceType)(nil),          // 8: control_service.DeviceType
	(*UseCase)(nil),             // 9: control_service.UseCase
	(*UseCaseEvent)(nil),        // 10: control_service.UseCaseEvent
	(*UseCase_ActorType)(nil),   // 11: control_service.UseCase.ActorType
	(*UseCase_NameType)(nil),    // 12: control_service.UseCase.NameType
}
var file_control_service_types_proto_depIdxs = []int32{
	4, // 0: control_service.UseCase.actor:type_name -> control_service.UseCase.ActorType.Enum
	5, // 1: control_service.UseCase.name:type_name -> control_service.UseCase.NameType.Enum
	9, // 2: control_service.UseCaseEvent.use_case:type_name -> control_service.UseCase
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_control_service_types_proto_init() }
func file_control_service_types_proto_init() {
	if File_control_service_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_service_types_proto_rawDesc), len(file_control_service_types_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_service_types_proto_goTypes,
		DependencyIndexes: file_control_service_types_proto_depIdxs,
		EnumInfos:         file_control_service_types_proto_enumTypes,
		MessageInfos:      file_control_service_types_proto_msgTypes,
	}.Build()
	File_control_service_types_proto = out.File
	file_control_service_types_proto_goTypes = nil
	file_control_service_types_proto_depIdxs = nil
}
